const CACHE='kc-dp2-pilot-v01951-auto1';
const META_CACHE='kc-dp2-pilot-meta-v1';
const META_URL=new URL('__kc_dp_pilot_context__',self.registration.scope).toString();
const PILOT_ENDPOINT='https://ptblnpiroqftcvlsrhac.supabase.co/functions/v1/kc-dp-pilot';
const SHELL=['./pilot/index.html','./pilot/manifest.webmanifest','./src/ui/pilot.css','./src/ui/pilot-app.js','./src/core/pilot-onboarding.js','./assets/kc-dp2-apple-touch-icon.png'];
self.addEventListener('install',event=>event.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(SHELL);await self.skipWaiting()})()));
self.addEventListener('activate',event=>event.waitUntil((async()=>{for(const k of await caches.keys())if(k.startsWith('kc-dp2-pilot-')&&k!==CACHE&&k!==META_CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const u=new URL(event.request.url);if(u.origin!==self.location.origin)return;event.respondWith((async()=>{try{const r=await fetch(event.request,{cache:'no-store'});if(r.ok){const c=await caches.open(CACHE);await c.put(event.request,r.clone())}return r}catch(_){return (await caches.match(event.request,{ignoreSearch:true}))||(await caches.match('./pilot/index.html'))||Response.error()}})())});
async function writeContext(ctx){const c=await caches.open(META_CACHE);await c.put(META_URL,new Response(JSON.stringify(ctx),{headers:{'Content-Type':'application/json'}}))}
async function readContext(){try{const c=await caches.open(META_CACHE),r=await c.match(META_URL);return r?await r.json():{}}catch(_){return{}}}
self.addEventListener('message',event=>{const d=event.data||{};if(d.type==='KC_DP_PILOT_CONTEXT')event.waitUntil(writeContext({token:String(d.token||''),deviceClass:String(d.deviceClass||''),device:String(d.device||''),updatedAt:new Date().toISOString()}).then(()=>event.ports?.[0]?.postMessage({ok:true})))});
async function reportReceipt(data){const ctx=await readContext(),token=String(ctx.token||''),action=data?.type==='test'?'test_received':data?.type==='complete'?'completion_received':'';if(!token||!action)return false;try{const r=await fetch(PILOT_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,device:ctx.device||'push-sw',deviceClass:ctx.deviceClass||''})});return r.ok}catch(_){return false}}
async function tellClients(data){const list=await clients.matchAll({type:'window',includeUncontrolled:true});for(const c of list)c.postMessage({type:'KC_DP_PILOT_PUSH_RECEIVED',data})}
self.addEventListener('push',event=>{let data={};try{data=event.data?.json?.()||{body:event.data?.text?.()||''}}catch(_){data={body:event.data?.text?.()||''}};event.waitUntil(Promise.all([self.registration.showNotification(data.title||'KC DP2 Pilot',{body:data.body||'',data:data.data||{},tag:`pilot-${data.data?.type||'msg'}`,renotify:true}),reportReceipt(data.data||{}),tellClients(data.data||{})]))});
self.addEventListener('notificationclick',event=>{event.notification.close();const data=event.notification.data||{},q=new URLSearchParams();if(data.route)q.set('route',data.route);if(data.type)q.set('type',data.type);const target='./pilot/index.html'+(q.toString()?'?'+q.toString():'');event.waitUntil((async()=>{const list=await clients.matchAll({type:'window',includeUncontrolled:true});for(const c of list){if(new URL(c.url).pathname.includes('/pilot/')&&'focus'in c){c.postMessage({type:'KC_DP_NOTIFICATION_OPEN',data});return c.focus()}}return clients.openWindow?clients.openWindow(target):undefined})())});
