(function(){
  'use strict';
  const K=window.KCDP=window.KCDP||{};
  const state={view:'day',dayIndex:Math.max(0,Number(K.state?.dateIndex)||0),editing:false,menu:false};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>Number.isFinite(Number(v))?Number(v):0;
  const fmtTime=h=>`${String(Math.floor(n(h))).padStart(2,'0')}:${String(Math.round((n(h)%1)*60)).padStart(2,'0')}`;
  const fmtDate=date=>new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(date+'T12:00:00'));
  const activeShift=s=>s?.layer==='planned'&&!['deleted','cancelled','absent','failed'].includes(String(s.status||''));
  function day(){state.dayIndex=Math.max(0,Math.min((K.days||[]).length-1,state.dayIndex));return K.days?.[state.dayIndex]}
  function rows(d){return K.configuration?.ensureDemand?.(d.date)||K.demandMatrix?.[d.date]||[]}
  function weatherIcon(w={}){const x=`${w.code||''} ${w.condition||w.summary||w.description||''}`.toLowerCase();if(/sturm|storm|orkan|warning/.test(x))return'⚠️🌬️';if(/schnee|snow/.test(x))return'❄️';if(/regen|rain|schauer|shower/.test(x))return'🌧️';if(/nebel|fog|mist/.test(x))return'🌫️';if(/wind|bö|boe/.test(x))return'💨';if(/sonn|sun|clear|klar/.test(x))return'☀️';if(/leicht.*bew|partly|wechselnd/.test(x))return'🌤️';return'☁️'}
  function weatherText(w={}){const condition=w.condition||w.summary||w.description||'keine Beschreibung',temp=Number.isFinite(Number(w.temp??w.temperature))?`${n(w.temp??w.temperature)} °C`:'';return `${condition}${temp?' · '+temp:''}`}
  function contextAt(d,start,end){const programs=(d.program||[]).filter(p=>n(p.start)<end&&n(p.end)>start),w=Array.isArray(d.weather?.hourly)?(d.weather.hourly.find(x=>n(x.start??x.hour)<end&&n(x.end??(n(x.start??x.hour)+1))>start)||d.weather):d.weather||{};return{programs,w}}
  function plannedAt(d,start,end){const list=(K.shifts||[]).filter(s=>activeShift(s)&&s.date===d.date&&n(s.start)<end&&n(s.end)>start),stand=list.filter(s=>s.zone!=='special'),front=stand.filter(s=>s.zone==='front').length,back=stand.filter(s=>s.zone==='back').length;return{total:stand.length,front,back}}
  function sourceStatus(d){const pc=K.pcManagerConnection?.state||{},health=K.sourceHealth?.snapshot?.(d.date),when=pc.lastSyncAt||d.weather?.fetchedAt||K.contextProviders?.state?.lastWeatherAt||K.contextProviders?.state?.lastProgramAt;return{label:health?.context?.status==='manager'?'PC Manager führend':health?.context?.status==='partial'?'PC Manager teilweise':'lokale/letzte Daten',when,error:pc.lastError||'',ready:health?.context?.status==='manager'}}
  function totals(d){let base=0,recommended=0,planned=0;for(const r of rows(d)){const duration=Math.max(0,n(r.end)-n(r.start)),req=K.requirementFor(d,n(r.start)),p=plannedAt(d,n(r.start),n(r.end));base+=n(r.total)*duration;recommended+=n(req.total)*duration;planned+=p.total*duration}return{base:Math.round(base*10)/10,recommended:Math.round(recommended*10)/10,planned:Math.round(planned*10)/10}}
  function controls(){const d=day(),editable=K.auth?.has?.('roster.matrix.edit');return `<div class="demand-nav"><button type="button" id="demandPrev" aria-label="Zurück">‹</button><button type="button" id="demandDate">${fmtDate(d.date)}</button><button type="button" id="demandNext" aria-label="Weiter">›</button>${state.view==='day'&&editable?`<button type="button" id="demandEditToggle" class="demand-edit-toggle ${state.editing?'active':''}" title="Bedarfswerte direkt mit Hoch-/Runter-Pfeilen bearbeiten" aria-pressed="${state.editing}">${state.editing?'✓ Bearbeitung aktiv':'✎ Bedarf bearbeiten'}</button>`:''}<div class="demand-segments" role="group" aria-label="Zeitraum"><button data-demand-view="day" class="${state.view==='day'?'active':''}">Tag</button><button data-demand-view="week" class="${state.view==='week'?'active':''}">Woche</button><button data-demand-view="all" class="${state.view==='all'?'active':''}">Zeitraum</button></div></div>`}
  function dayTable(d){const editable=K.auth?.has?.('roster.matrix.edit');return `<div class="demand-table-wrap"><table class="demand-table"><thead><tr><th>Zeit</th><th>Grundbedarf</th><th>Vorne</th><th>Hinten</th><th>Flexibel</th><th>Wetter</th><th>Bühnenprogramm</th><th>Empfehlung</th><th>Soll</th></tr></thead><tbody>${rows(d).map((r,i)=>{const req=K.requirementFor(d,n(r.start)),ctx=contextAt(d,n(r.start),n(r.end)),p=plannedAt(d,n(r.start),n(r.end)),simple=r.front==null||r.back==null,flex=simple?n(r.total):0,delta=n(req.total)-n(r.total),gap=p.total-n(req.total);return `<tr data-demand-row="${i}" data-extra="${delta}" data-duration="${Math.max(0,n(r.end)-n(r.start))}" data-planned="${p.total}" class="${gap<0?'under':gap>0?'over':''}"><td><b>${fmtTime(r.start)}–${fmtTime(r.end)}</b></td><td>${state.editing?`<input data-field="total" type="number" min="0" step="1" value="${n(r.total)}" aria-label="Grundbedarf gesamt">`:`<b>${n(r.total)}</b>`}</td><td>${state.editing&&!simple?`<input data-field="front" type="number" min="0" step="1" value="${n(r.front)}" aria-label="Bedarf vorne">`:simple?'–':n(r.front)}</td><td>${state.editing&&!simple?`<input data-field="back" type="number" min="0" step="1" value="${n(r.back)}" aria-label="Bedarf hinten">`:simple?'–':n(r.back)}</td><td>${flex||'–'}${simple?'<small>Qualifikation/Bereich egal</small>':''}</td><td><span class="demand-weather">${weatherIcon(ctx.w)} <span>${esc(weatherText(ctx.w))}</span></span></td><td>${ctx.programs.length?ctx.programs.map(x=>`<span class="demand-program">${/kind|kinder/i.test(x.title||'')?'🧒':/band|musik|chor/i.test(x.title||'')?'🎤':'🎭'} ${esc(x.title||'Programmpunkt')}<small>${fmtTime(x.start)}–${fmtTime(x.end)}</small></span>`).join(''):'–'}</td><td data-demand-recommendation><b>${n(req.total)}</b>${delta?`<small>${delta>0?'+':''}${delta} · ${esc((req.explanation||[]).slice(1).join(', '))}</small>`:'<small>wie Grundbedarf</small>'}</td><td data-demand-planned><b>${p.total}</b><small>${simple?'flexibel':`${p.front} V / ${p.back} H`}${gap<0?` · fehlen ${Math.abs(gap)}`:gap>0?` · +${gap}`:' · passend'}</small></td></tr>`}).join('')}</tbody></table></div>${state.editing?`<div class="demand-savebar"><span class="demand-live-note">Änderungen werden sofort neu berechnet.</span><button id="demandCancel">Abbrechen</button><button id="demandSave" class="primary" ${editable?'':'disabled'}>Grundbedarf speichern</button></div>`:''}`}
  function dayView(d){const t=totals(d),src=sourceStatus(d),w=d.weather||{},program=d.program||[],next=program[0];return `<div class="demand-context"><div class="demand-weather-large"><span>${weatherIcon(w)}</span><div><b>${esc(weatherText(w))}</b><small>${esc(w.windSpeed!=null?`Wind ${w.windSpeed} km/h · `:'')}${esc(src.label)}</small></div></div><div class="demand-program-summary"><span>${next&&/kind|kinder/i.test(next.title||'')?'🧒':next&&/band|musik|chor/i.test(next.title||'')?'🎤':'🎭'}</span><div><b>${program.length?`${program.length} Programmpunkt(e)`: 'Kein Bühnenprogramm'}</b><small>${next?`nächster: ${esc(next.title||'Programm')} ${fmtTime(next.start)}–${fmtTime(next.end)}`:'für diesen Tag'}</small></div></div><div class="demand-source ${src.ready?'ready':''}"><b>PC Manager</b><span>${src.when?`Stand ${new Date(src.when).toLocaleString('de-DE')}`:'noch kein synchronisierter Datenstand'}</span>${src.error?`<small>${esc(src.error)}</small>`:''}</div></div><div class="demand-kpis"><div><small>Grundbedarf</small><b data-demand-kpi="base">${t.base} h</b></div><div><small>Empfehlung</small><b data-demand-kpi="recommended">${t.recommended} h</b></div><div><small>Soll</small><b data-demand-kpi="planned">${t.planned} h</b></div><div><small>Abweichung Soll/Empfehlung</small><b data-demand-kpi="delta">${t.planned-t.recommended>=0?'+':''}${Math.round((t.planned-t.recommended)*10)/10} h</b></div></div>${dayTable(d)}`}
  function rangeDays(){if(state.view==='all')return K.days||[];const d=day(),monday=new Date(d.date+'T12:00:00'),weekday=(monday.getDay()+6)%7;monday.setDate(monday.getDate()-weekday);const start=monday.toISOString().slice(0,10),end=new Date(monday.getTime()+6*86400000).toISOString().slice(0,10);return (K.days||[]).filter(x=>x.date>=start&&x.date<=end)}
  function summary(){const selected=day()?.date;return `<div class="demand-daycards">${rangeDays().map((d,i)=>{const t=totals(d),w=d.weather||{},g=Math.round((t.planned-t.recommended)*10)/10,weekend=[0,6].includes(new Date(d.date+'T12:00:00').getDay()),current=d.date===selected;return `<button type="button" data-demand-date="${d.date}" class="demand-daycard ${d.type!=='market'?'striped ':''}${weekend?'weekend ':''}${current?'current-day':''}" ${current?'aria-current="date"':''}><span class="demand-day-title"><b>${fmtDate(d.date)}</b><span>${weatherIcon(w)} ${esc(weatherText(w))}</span></span><span><small>Grundbedarf</small><b>${t.base} h</b></span><span><small>Empfehlung</small><b>${t.recommended} h</b></span><span><small>Sollabweichung</small><b>${g>=0?'+':''}${g} h</b></span><span><small>Bühne</small><b>${(d.program||[]).length} Programmpunkt(e)</b></span></button>`}).join('')}</div>`}
  function render(){if(document.body.dataset.v020Register!=='demand')return;const host=document.getElementById('mainView'),d=day();if(!host||!d)return;host.innerHTML=`<section class="demand-view"><header class="demand-head"><div><h1>Bedarf</h1><p>Tägliche Besetzungsmatrix mit nachvollziehbaren PC-Manager-Einflüssen.</p></div></header>${controls()}<div class="demand-note"><b>Grundbedarf bleibt verbindlich getrennt:</b> Wetter und Bühnenprogramm erzeugen eine begründete Empfehlung. B-Personen sind flexibel für V oder H und werden niemals doppelt gezählt.</div>${state.view==='day'?dayView(d):summary()}</section>`;bind()}
  function setText(selector,value){const el=document.querySelector(selector);if(el)el.textContent=value}
  function recalculateDraft(){let base=0,recommended=0,planned=0;const d=day(),sourceRows=rows(d);document.querySelectorAll('[data-demand-row]').forEach(tr=>{const total=n(tr.querySelector('[data-field="total"]')?.value),source=sourceRows[Number(tr.dataset.demandRow)],req=K.requirementFor(d,n(source?.start)),weatherExtra=Math.round(total*(n(d.weather?.factor||1)-1)),extra=weatherExtra+n(req.programExtra),duration=n(tr.dataset.duration),plan=n(tr.dataset.planned),recommendation=Math.max(0,total+extra),gap=plan-recommendation,front=tr.querySelector('[data-field="front"]'),back=tr.querySelector('[data-field="back"]');base+=total*duration;recommended+=recommendation*duration;planned+=plan*duration;tr.classList.toggle('under',gap<0);tr.classList.toggle('over',gap>0);const rec=tr.querySelector('[data-demand-recommendation]'),planCell=tr.querySelector('[data-demand-planned]');if(rec)rec.innerHTML=`<b>${recommendation}</b>${extra?`<small>${extra>0?'+':''}${extra} · Wetter/Programm</small>`:'<small>wie Grundbedarf</small>'}`;if(planCell)planCell.innerHTML=`<b>${plan}</b><small>${front&&back?`${n(front.value)} V / ${n(back.value)} H`: 'flexibel'}${gap<0?` · fehlen ${Math.abs(gap)}`:gap>0?` · +${gap}`:' · passend'}</small>`});const round=x=>Math.round(x*10)/10,delta=round(planned-recommended);setText('[data-demand-kpi="base"]',`${round(base)} h`);setText('[data-demand-kpi="recommended"]',`${round(recommended)} h`);setText('[data-demand-kpi="planned"]',`${round(planned)} h`);setText('[data-demand-kpi="delta"]',`${delta>=0?'+':''}${delta} h`)}
  function changeDemandInput(e){const input=e.target.closest?.('[data-field]');if(!input)return;const tr=input.closest('[data-demand-row]'),total=tr.querySelector('[data-field="total"]'),front=tr.querySelector('[data-field="front"]'),back=tr.querySelector('[data-field="back"]');input.value=Math.max(0,Math.round(n(input.value)));if(front&&back){if(input===total){const wanted=n(total.value),frontValue=Math.min(wanted,n(front.value));front.value=frontValue;back.value=Math.max(0,wanted-frontValue)}else total.value=n(front.value)+n(back.value)}recalculateDraft()}
  function bind(){document.getElementById('demandPrev')?.addEventListener('click',()=>{state.dayIndex=Math.max(0,state.dayIndex-(state.view==='week'?7:1));render()});document.getElementById('demandNext')?.addEventListener('click',()=>{state.dayIndex=Math.min(K.days.length-1,state.dayIndex+(state.view==='week'?7:1));render()});document.getElementById('demandDate')?.addEventListener('click',()=>{const v=prompt('Datum JJJJ-MM-TT:',day().date),i=K.days.findIndex(d=>d.date===v);if(i>=0){state.dayIndex=i;render()}});document.getElementById('demandEditToggle')?.addEventListener('click',()=>{state.editing=!state.editing;render()});document.querySelectorAll('[data-demand-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.demandView;if(state.view!=='day')state.editing=false;render()}));document.querySelectorAll('[data-demand-date]').forEach(b=>b.addEventListener('click',()=>{state.dayIndex=K.days.findIndex(d=>d.date===b.dataset.demandDate);state.view='day';render()}));document.querySelectorAll('[data-demand-row] input[data-field]').forEach(input=>input.addEventListener('input',changeDemandInput));document.getElementById('demandCancel')?.addEventListener('click',()=>{state.editing=false;render()});document.getElementById('demandSave')?.addEventListener('click',save)}
  async function save(){const d=day(),current=rows(d);try{document.querySelectorAll('[data-demand-row]').forEach(tr=>{const r=current[Number(tr.dataset.demandRow)],total=n(tr.querySelector('[data-field="total"]')?.value??r.total),front=r.front==null?null:n(tr.querySelector('[data-field="front"]')?.value),back=r.back==null?null:n(tr.querySelector('[data-field="back"]')?.value);K.configuration.setDemandInterval(d.date,r.start,r.end,{total,front,back,requiredRoles:r.requiredRoles||[]})});state.editing=false;await K.persistAll?.();render()}catch(e){alert(e.message)}}
  async function sync(){try{await K.pcManagerConnection?.syncAll?.();await K.persistAll?.();state.menu=false;render()}catch(e){alert('PC-Manager-Synchronisierung fehlgeschlagen: '+e.message)}}
  async function copy(){const target=prompt('Bedarf von '+day().date+' auf welches Datum kopieren? (JJJJ-MM-TT)','');if(!K.days.some(d=>d.date===target))return target&&alert('Datum gehört nicht zum Planzeitraum.');if(!confirm(`Grundbedarf für ${target} ersetzen?`))return;K.configuration.copyDemand(day().date,target);await K.persistAll?.();state.menu=false;render()}
  window.addEventListener('kc-v020-register-change',e=>{if(e.detail?.id==='demand')render()});window.addEventListener('kc-dp-data-loaded',()=>{if(document.body.dataset.v020Register==='demand')render()});
  K.demandView={version:'0.20.0-b116',state,render,weatherIcon,totals,sync,copy,edit(){state.editing=true;state.menu=false;render()}};
})();
