(function(){
  'use strict';
  const K=window.KCDP=window.KCDP||{},state={range:'day',dayIndex:Math.max(0,K.state?.dateIndex||0),filter:'all',team:'all',open:null};
  const active=x=>x&&!['deleted','cancelled','absent','failed'].includes(x.status),n=v=>Number(v)||0,round=v=>Math.round(n(v)*10)/10;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const tm=h=>`${String(Math.floor(n(h))).padStart(2,'0')}:${String(Math.round((n(h)%1)*60)).padStart(2,'0')}`;
  const fmt=d=>new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}).format(new Date(d+'T12:00:00'));
  const hours=list=>round(list.reduce((sum,x)=>sum+Math.max(0,n(x.end)-n(x.start)-(n(x.breakMinutes)/60)),0));
  const team=p=>String(p.team||p.department||p.group||p.personType||'Ohne Teamangabe');
  function day(){state.dayIndex=Math.max(0,Math.min((K.days||[]).length-1,state.dayIndex));return K.days?.[state.dayIndex]}
  function dates(){const d=day();if(!d)return[];if(state.range==='day')return[d];if(state.range==='all')return K.days||[];const dt=new Date(d.date+'T12:00:00'),wd=(dt.getDay()+6)%7;dt.setDate(dt.getDate()-wd);const a=dt.toISOString().slice(0,10);dt.setDate(dt.getDate()+6);const z=dt.toISOString().slice(0,10);return (K.days||[]).filter(x=>x.date>=a&&x.date<=z)}
  const interval=list=>list.length?list.map(x=>`${tm(x.start)}–${tm(x.end)}`).join(', '):'–';
  function rows(){const ds=new Set(dates().map(d=>d.date)),out=[];for(const p of (K.people||[]).filter(x=>x.active!==false&&(state.team==='all'||team(x)===state.team))){for(const date of ds){const wishes=(K.wishes||[]).filter(x=>active(x)&&x.personId===p.personId&&x.date===date),wish=wishes.filter(x=>x.wishType==='preferred'),can=wishes.filter(x=>['available','if_needed'].includes(x.wishType)),blocked=wishes.filter(x=>x.wishType==='unavailable'),planned=(K.shifts||[]).filter(x=>active(x)&&x.layer==='planned'&&x.personId===p.personId&&x.date===date),actual=(K.actualShifts||[]).filter(x=>active(x)&&x.personId===p.personId&&x.date===date);actual.forEach(x=>K.actual?.linkRecord?.(x));const wh=hours(wish),sh=hours(planned),ih=hours(actual),dsw=round(sh-wh),dis=round(ih-sh),missing=!planned.length&&!!wish.length||!actual.length&&!!planned.length,changed=Math.abs(dsw)>.01||Math.abs(dis)>.01||blocked.length;if(wish.length||can.length||planned.length||actual.length||blocked.length)out.push({p,date,wish,can,blocked,planned,actual,wh,sh,ih,dsw,dis,missing,changed})}}
    return out.filter(x=>state.filter==='all'||state.filter==='changed'&&x.changed||state.filter==='missing'&&x.missing||state.filter==='critical'&&(Math.abs(x.dsw)>=2||Math.abs(x.dis)>=2));
  }
  function delta(v){return `<span class="dev-delta ${v>0?'plus':v<0?'minus':'zero'}">${v>0?'+':''}${String(v).replace('.',',')} h</span>`}
  function mini(r){const d=(K.days||[]).find(x=>x.date===r.date),start=n(d?.start),end=n(d?.end)||24,span=Math.max(1,end-start),bar=(list,cls)=>list.map(x=>`<i class="${cls}" style="left:${Math.max(0,(n(x.start)-start)/span*100)}%;width:${Math.max(1,(n(x.end)-n(x.start))/span*100)}%"></i>`).join('');return `<div class="dev-mini" title="Wunsch, Soll und Ist im Tagesverlauf"><span>${bar(r.wish,'wish')}</span><span>${bar(r.planned,'planned')}</span><span>${bar(r.actual,'actual')}</span></div>`}
  function controls(){const d=day(),weekend=d&&[0,6].includes(new Date(d.date+'T12:00:00').getDay());return `<div class="dev-controls"><button id="devPrev" title="Zurück">‹</button><button id="devDate" class="${d?.type!=='market'?'striped ':''}${weekend?'weekend':''}" title="Tag auswählen">${fmt(d.date)}</button><button id="devNext" title="Weiter">›</button><div class="dev-segment">${[['day','T','Tagesansicht'],['week','W','Wochenansicht'],['all','Z','Gesamter Zeitraum']].map(([v,l,t])=>`<button data-dev-range="${v}" class="${state.range===v?'active':''}" title="${t}">${l}</button>`).join('')}</div><label>Team<select id="devTeam"><option value="all">Alle Teams</option>${[...new Set((K.people||[]).map(team))].sort().map(x=>`<option value="${esc(x)}" ${state.team===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Anzeige<select id="devFilter"><option value="all">Alle Einträge</option><option value="changed" ${state.filter==='changed'?'selected':''}>Mit Abweichung</option><option value="missing" ${state.filter==='missing'?'selected':''}>Fehlende Stufe</option><option value="critical" ${state.filter==='critical'?'selected':''}>Ab 2 Stunden</option></select></label></div>`}
  function detail(r){if(!r)return'';const warnings=[r.blocked.length?'Sperrzeit/Sperrtag vorhanden':'',r.missing?'Mindestens eine Planstufe fehlt':''].filter(Boolean);return `<aside class="dev-detail"><header><div><small>Abweichungsdetail</small><h2>${esc(r.p.name)}</h2><p>${fmt(r.date)}</p></div><button id="devClose">×</button></header>${warnings.length?`<div class="dev-warning">${warnings.join(' · ')}</div>`:''}<div class="dev-detail-grid"><article><b>Wunsch</b><span>${interval(r.wish)}</span><small>${r.wh} h · Kann ${interval(r.can)}</small></article><article><b>Soll</b><span>${interval(r.planned)}</span><small>${r.sh} h · Δ Wunsch ${r.dsw>0?'+':''}${r.dsw} h</small></article><article><b>Ist</b><span>${interval(r.actual)}</span><small>${r.ih} h · Δ Soll ${r.dis>0?'+':''}${r.dis} h</small></article></div><section><h3>Einträge</h3>${r.planned.map(x=>`<button data-dev-plan="${x.id}">Soll ${tm(x.start)}–${tm(x.end)} bearbeiten</button>`).join('')}${r.actual.map(x=>`<button data-dev-actual="${x.id}">Ist ${tm(x.start)}–${tm(x.end)} korrigieren</button>`).join('')}<button id="devWish">Wunschmatrix öffnen</button></section></aside>`}
  function render(){if(document.body.dataset.v020Register!=='deviations')return;const host=document.getElementById('mainView');if(!host)return;const list=rows(),allHours={wish:round(list.reduce((s,x)=>s+x.wh,0)),planned:round(list.reduce((s,x)=>s+x.sh,0)),actual:round(list.reduce((s,x)=>s+x.ih,0))},open=list.find(x=>`${x.p.personId}|${x.date}`===state.open);host.innerHTML=`<section class="deviations-view"><header><h1>Abweichungen</h1><p>Wunsch, Soll und Ist je Person transparent gegenüberstellen.</p></header>${controls()}<div class="dev-kpis"><article><small>Fälle</small><b>${list.length}</b></article><article><small>Wunschstunden</small><b>${allHours.wish} h</b></article><article><small>Sollstunden</small><b>${allHours.planned} h</b></article><article><small>Iststunden</small><b>${allHours.actual} h</b></article><article><small>Fehlende Stufe</small><b>${list.filter(x=>x.missing).length}</b></article></div><div class="dev-table-wrap"><table><thead><tr><th>Person / Tag</th><th>Zeitvergleich</th><th>Wunsch</th><th>Soll</th><th>Δ W→S</th><th>Ist</th><th>Δ S→I</th></tr></thead><tbody>${list.map(r=>`<tr data-dev-row="${r.p.personId}|${r.date}" class="${r.missing?'missing':''}"><th><b>${esc(r.p.name)}</b><small>${fmt(r.date)} · ${esc(team(r.p))}</small></th><td>${mini(r)}</td><td>${interval(r.wish)}<small>${r.wh} h</small></td><td>${interval(r.planned)}<small>${r.sh} h</small></td><td>${delta(r.dsw)}</td><td>${interval(r.actual)}<small>${r.ih} h</small></td><td>${delta(r.dis)}</td></tr>`).join('')||'<tr><td colspan="7">Keine Einträge im gewählten Bereich.</td></tr>'}</tbody></table></div>${detail(open)}</section>`;bind(list)}
  const parse=v=>{const[a,b]=String(v).split(':').map(Number);return a+b/60};
  function editPlan(id){const s=K.shifts.find(x=>x.id===id);if(!s)return;const a=prompt('Soll von HH:MM',tm(s.start));if(a==null)return;const e=prompt('Soll bis HH:MM',tm(s.end));if(e==null)return;try{K.mutations.saveShift({...s,start:parse(a),end:parse(e)},{existingId:s.id,reason:'Abweichungsansicht: Soll angepasst'});K.persistAll?.();render()}catch(err){alert(err.message)}}
  function editActual(id){const a=(K.actualShifts||[]).find(x=>x.id===id);if(!a)return;const s=prompt('Ist von HH:MM',tm(a.start));if(s==null)return;const e=prompt('Ist bis HH:MM',tm(a.end));if(e==null)return;const reason=prompt('Korrekturgrund (Pflicht)','Abweichungsansicht geprüft');if(reason==null)return;try{K.actual.correctActual(a.id,{start:parse(s),end:parse(e)},{reason});K.persistAll?.();render()}catch(err){alert(err.message)}}
  function bind(list){document.getElementById('devPrev')?.addEventListener('click',()=>{state.dayIndex=Math.max(0,state.dayIndex-(state.range==='week'?7:1));state.open=null;render()});document.getElementById('devNext')?.addEventListener('click',()=>{state.dayIndex=Math.min(K.days.length-1,state.dayIndex+(state.range==='week'?7:1));state.open=null;render()});document.getElementById('devDate')?.addEventListener('click',e=>K.dayPicker?.open(e.currentTarget,{currentIndex:state.dayIndex,title:'Abweichungen: Tag auswählen',onSelect:i=>{state.dayIndex=i;state.open=null;render()}}));document.querySelectorAll('[data-dev-range]').forEach(b=>b.onclick=()=>{state.range=b.dataset.devRange;state.open=null;render()});document.getElementById('devTeam').onchange=e=>{state.team=e.target.value;state.open=null;render()};document.getElementById('devFilter').onchange=e=>{state.filter=e.target.value;state.open=null;render()};document.querySelectorAll('[data-dev-row]').forEach(b=>b.onclick=()=>{state.open=b.dataset.devRow;render()});document.getElementById('devClose')?.addEventListener('click',()=>{state.open=null;render()});document.querySelectorAll('[data-dev-plan]').forEach(b=>b.onclick=e=>{e.stopPropagation();editPlan(b.dataset.devPlan)});document.querySelectorAll('[data-dev-actual]').forEach(b=>b.onclick=e=>{e.stopPropagation();editActual(b.dataset.devActual)});document.getElementById('devWish')?.addEventListener('click',()=>{const [personId,date]=state.open.split('|');K.planTransfer?.matrixEditor?.(personId,date)})}
  function install(){window.addEventListener('kc-v020-register-change',e=>{if(e.detail?.id==='deviations'){state.dayIndex=Math.max(0,K.state?.dateIndex||0);setTimeout(render,0)}});if(document.body.dataset.v020Register==='deviations')render()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();K.deviationsView={version:'0.20.0-b106',state,rows,render};
})();
