(function(){
'use strict';
var K=window.KCDP=window.KCDP||{};
var state={scope:'all',team:'all',activity:'all',sort:'delta',dir:'desc',query:'',open:null,info:false,distribution:true};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function n(v){v=Number(v);return Number.isFinite(v)?v:0}
function round(v){return Math.round(n(v)*10)/10}
function fmt(v){return round(v).toLocaleString('de-DE',{minimumFractionDigits:1,maximumFractionDigits:1})+' h'}
function active(s){return !['deleted','cancelled','absent','failed'].includes(String((s&&s.status)||''))}
function hours(s){return K.breaks&&K.breaks.countedHours?K.breaks.countedHours(s):Math.max(0,n(s.end)-n(s.start)-n(s.breakMinutes)/60)}
function range(){var dates=(K.days||[]).map(function(d){return d.date}).sort();if(!dates.length)return{start:'',end:''};var anchor=(K.day&&K.day()&&K.day().date)||dates[0],i=Math.max(0,dates.indexOf(anchor));if(state.scope==='day')return{start:anchor,end:anchor};if(state.scope==='week')return{start:dates[Math.max(0,i-3)],end:dates[Math.min(dates.length-1,i+3)]};return{start:dates[0],end:dates[dates.length-1]}}
function inside(x,r){return x&&x.date>=r.start&&x.date<=r.end}
function team(p){return String(p.team||p.department||p.group||p.personType||'Ohne Teamangabe')}
function availability(p,r){return round((p.availability||[]).filter(function(a){return inside(a,r)}).reduce(function(sum,a){return sum+Math.max(0,n(a.end)-n(a.start))},0))}
function target(p){var keys=['targetHours','eventTargetHours','contractHours','weeklyTargetHours'];for(var i=0;i<keys.length;i++){var v=p[keys[i]]!=null?p[keys[i]]:p.rules&&p.rules[keys[i]];if(v!=null&&n(v)>=0)return{value:n(v),label:'persönlich hinterlegte Sollstunden'}}return null}
function segment(list,a,b){return round(list.reduce(function(sum,s){return sum+Math.max(0,Math.min(n(s.end),b)-Math.max(n(s.start),a))},0))}
function dataRows(){
 var r=range(),actual=(K.actualShifts||[]).filter(function(s){return active(s)&&inside(s,r)}),planned=(K.shifts||[]).filter(function(s){return s.layer==='planned'&&active(s)&&inside(s,r)}),hasActual=actual.length>0;
 var people=(K.people||[]).filter(function(p){return p.active!==false&&p.personType!=='system'});
 if(state.team!=='all')people=people.filter(function(p){return team(p)===state.team});
 var raw=people.map(function(p){var filter=function(s){return s.personId===p.personId&&(state.activity==='all'||String(s.area||s.zone||'Ohne Tätigkeitsangabe')===state.activity)},pa=planned.filter(filter),ac=actual.filter(filter),used=hasActual?ac:pa,sum=function(a){return round(a.reduce(function(t,s){return t+hours(s)},0))};return{p:p,planned:sum(pa),actual:sum(ac),value:sum(used),available:availability(p,r),front:sum(used.filter(function(s){return s.zone==='front'})),back:sum(used.filter(function(s){return s.zone==='back'})),special:sum(used.filter(function(s){return s.zone==='special'})),early:segment(used,11,15),middle:segment(used,15,18),late:segment(used,18,30),services:used.length,weekend:used.filter(function(s){return[0,6].includes(new Date(s.date+'T12:00:00').getDay())}).length}});
 var avg=raw.length?round(raw.reduce(function(t,x){return t+x.value},0)/raw.length):0;
 return{range:r,hasActual:hasActual,rows:raw.map(function(x){var fixed=target(x.p),reference,basis;if(fixed){reference=round(fixed.value);basis=fixed.label}else if(x.available>0){reference=x.available;basis='hinterlegte Verfügbarkeit'}else{reference=avg;basis=(hasActual?'Ist':'Sollplan')+'-Teamdurchschnitt'}return Object.assign(x,{reference:reference,basis:basis,delta:round(x.value-reference)})})}
}
function status(x){var limit=Math.max(1,Math.min(4,x.reference*.15));if(Math.abs(x.delta)<=limit)return{key:'ok',label:'Im Toleranzbereich'};if(x.delta<0)return{key:'low',label:fmt(Math.abs(x.delta))+' unter Vergleich'};return{key:'high',label:fmt(x.delta)+' über Vergleich'}}
function median(a){a=a.slice().sort(function(x,y){return x-y});var m=Math.floor(a.length/2);return a.length?(a.length%2?a[m]:(a[m-1]+a[m])/2):0}
function opts(items,value){return items.map(function(x){return'<option value="'+esc(x)+'" '+(x===value?'selected':'')+'>'+esc(x)+'</option>'}).join('')}
function csv(){var d=dataRows(),head=['Mitarbeiter/in','Team',d.hasActual?'Ist h':'Soll h','Vergleich h','Differenz h','Vorne h','Hinten h','Z h','11-15 h','15-18 h','ab 18 h','Dienste','Wochenende','Datenbasis'],table=[head].concat(d.rows.map(function(x){return[x.p.name,team(x.p),x.value,x.reference,x.delta,x.front,x.back,x.special,x.early,x.middle,x.late,x.services,x.weekend,x.basis]})),text='﻿'+table.map(function(row){return row.map(function(v){return'"'+String(v==null?'':v).replace(/"/g,'""')+'"'}).join(';')}).join('\r\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='KC-DP2-Fairnis_'+d.range.start+'_'+d.range.end+'.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url)},0)}
function render(){
 if(document.body.dataset.v020Register!=='fairness')return;var host=document.getElementById('mainView');if(!host)return;
 var d=dataRows(),list=d.rows,teams=[...new Set((K.people||[]).filter(function(p){return p.active!==false}).map(team))].sort(),activities=[...new Set((K.actualShifts||[]).concat(K.shifts||[]).map(function(s){return String(s.area||s.zone||'Ohne Tätigkeitsangabe')}))].sort(),q=state.query.trim().toLowerCase();
 var shown=list.filter(function(x){return!q||(x.p.name+' '+team(x.p)+' '+x.basis).toLowerCase().includes(q)});
 shown.sort(function(a,b){var A=state.sort==='name'?a.p.name:state.sort==='hours'?a.value:state.sort==='status'?Math.abs(a.delta):a.delta,B=state.sort==='name'?b.p.name:state.sort==='hours'?b.value:state.sort==='status'?Math.abs(b.delta):b.delta,v=typeof A==='string'?A.localeCompare(B,'de'):A-B;return state.dir==='asc'?v:-v});
 var total=round(list.reduce(function(t,x){return t+x.value},0)),avg=list.length?round(total/list.length):0,under=list.filter(function(x){return status(x).key==='low'}).length,over=list.filter(function(x){return status(x).key==='high'}).length,ok=list.length-under-over,balance=list.length?Math.round(ok/list.length*100):100,worst=list.slice().sort(function(a,b){return Math.abs(b.delta)-Math.abs(a.delta)})[0];
 var rows=shown.map(function(x){var st=status(x),open=state.open===x.p.personId;return'<tr class="fairness-data-row" data-person="'+esc(x.p.personId)+'" data-tone="'+st.key+'" tabindex="0"><td><b>'+esc(x.p.name)+'</b></td><td>'+esc(team(x.p))+'</td><td><b>'+fmt(x.value)+'</b></td><td>'+fmt(x.reference)+'</td><td class="fairness-number '+(x.delta<0?'negative':x.delta>0?'positive':'')+'">'+(x.delta>=0?'+':'')+fmt(x.delta)+'</td><td>'+fmt(x.front)+'</td><td>'+fmt(x.back)+'</td><td>'+fmt(x.special)+'</td><td>'+fmt(x.early)+'</td><td>'+fmt(x.middle)+'</td><td>'+fmt(x.late)+'</td><td>'+x.services+'</td><td><span class="fairness-badge" data-tone="'+st.key+'"><i></i>'+esc(st.label)+'</span></td><td class="fairness-chevron">'+(open?'▴':'▾')+'</td></tr>'+(open?'<tr class="fairness-detail-row"><td colspan="14"><div><span><b>Vergleichsbasis</b>'+esc(x.basis)+'</span><span><b>Sollplan</b>'+fmt(x.planned)+'</span><span><b>Ist erfasst</b>'+fmt(x.actual)+'</span><span><b>Verfügbarkeit</b>'+fmt(x.available)+'</span><span><b>Wochenenddienste</b>'+x.weekend+'</span><span><b>Einordnung</b>'+esc(st.label)+'</span></div><p>'+(x.delta<0?'Unter der Vergleichsbasis: Verfügbarkeit, Abwesenheiten und weitere Einplanung prüfen.':x.delta>0?'Über der Vergleichsbasis: mögliche Verteilung auf andere verfügbare Personen prüfen.':'Die Verteilung liegt innerhalb der Toleranz.')+'</p></td></tr>':'')}).join('');
 var dist=function(key){return fmt(list.reduce(function(t,x){return t+x[key]},0))};
 host.innerHTML='<section class="fairness-view"><div class="fairness-toolbar"><div class="fairness-title"><h1>Fairnis</h1><span>'+esc(d.range.start)+' bis '+esc(d.range.end)+'</span></div><label>Zeitraum<select id="fairScope"><option value="all" '+(state.scope==='all'?'selected':'')+'>Gesamter Plan</option><option value="week" '+(state.scope==='week'?'selected':'')+'>7 Tage</option><option value="day" '+(state.scope==='day'?'selected':'')+'>Plantag</option></select></label><label>Team<select id="fairTeam"><option value="all">Alle Teams</option>'+opts(teams,state.team)+'</select></label><label>Tätigkeit<select id="fairActivity"><option value="all">Alle Tätigkeiten</option>'+opts(activities,state.activity)+'</select></label><label class="fairness-search">Suchen<input id="fairSearch" value="'+esc(state.query)+'" placeholder="Name oder Team"></label><button class="fairness-icon-btn" id="fairInfo">ⓘ Erklärung</button><button class="fairness-icon-btn" id="fairCsv">CSV</button><button class="fairness-icon-btn" id="fairPrint">Drucken</button></div>'+
 '<div class="fairness-status" data-tone="'+(under?'warn':'ok')+'"><span class="fairness-led"></span><b>'+(d.hasActual?(under?'Handlungsbedarf: '+under+' Person(en) unter dem Vergleichswert.':'Die Iststunden liegen weitgehend im Toleranzbereich.'):'Vorläufige Sollplan-Auswertung: '+under+' unter, '+over+' über und '+ok+' im Toleranzbereich.')+'</b><span>'+(d.hasActual?'Grundlage: erfasste Istzeiten':'Noch keine Istzeiten – Grundlage ist der Sollplan')+'</span></div>'+
 (state.info?'<div class="fairness-explanation"><b>Lesart:</b> Die Differenz vergleicht '+(d.hasActual?'Iststunden':'Sollplanstunden')+' mit persönlichem Soll, Verfügbarkeit oder Teamdurchschnitt. Grün = Toleranz, Rot = darunter, Gelb = darüber. Die Ansicht unterstützt die Planung und bewertet keine Person.</div>':'')+
 '<div class="fairness-kpis"><div><small>Bewertete Personen</small><strong>'+list.length+'</strong><span>'+shown.length+' sichtbar</span></div><div><small>'+(d.hasActual?'Iststunden':'Sollplanstunden')+'</small><strong>'+fmt(total)+'</strong><span>Ø '+fmt(avg)+' · Median '+fmt(median(list.map(function(x){return x.value})))+'</span></div><div data-tone="'+(balance>=70?'ok':balance>=45?'warn':'bad')+'"><small>Im Toleranzbereich</small><strong>'+balance+' %</strong><span>'+ok+' von '+list.length+'</span></div><div data-tone="'+(under?'bad':'ok')+'"><small>Unter Vergleich</small><strong>'+under+'</strong><span>'+over+' darüber</span></div><div><small>Größte Abweichung</small><strong>'+(worst?(worst.delta>=0?'+':'')+fmt(worst.delta):'–')+'</strong><span>'+esc(worst?worst.p.name:'keine')+'</span></div></div>'+
 '<div class="fairness-table-card"><div class="fairness-table-head"><div><b>Personenvergleich</b><span>'+shown.length+' Zeilen · Klick öffnet Begründung</span></div><label>Sortierung<select id="fairSort"><option value="delta" '+(state.sort==='delta'?'selected':'')+'>Differenz</option><option value="status" '+(state.sort==='status'?'selected':'')+'>Auffälligkeit</option><option value="hours" '+(state.sort==='hours'?'selected':'')+'>Stunden</option><option value="name" '+(state.sort==='name'?'selected':'')+'>Name</option></select></label><button id="fairDirection">'+(state.dir==='asc'?'Aufsteigend ↑':'Absteigend ↓')+'</button></div><div class="fairness-table-wrap"><table class="fairness-table"><thead><tr><th>Mitarbeiter/in</th><th>Team</th><th>'+(d.hasActual?'Ist':'Soll')+'</th><th>Vergleich</th><th>Differenz</th><th>V</th><th>H</th><th>Z</th><th>11–15</th><th>15–18</th><th>ab 18</th><th>Dienste</th><th>Status</th><th></th></tr></thead><tbody>'+(rows||'<tr><td colspan="14" class="fairness-empty">Keine Personen für diese Auswahl.</td></tr>')+'</tbody></table></div></div>'+
 '<section class="fairness-fold"><button id="fairDistribution"><span>'+(state.distribution?'⌃':'⌄')+'</span><b>Verteilung nach Dienstart und Zeitlage</b><small>V/H/Z und Tageszeiten</small></button>'+(state.distribution?'<div class="fairness-distribution"><div><b>Vorne</b><strong>'+dist('front')+'</strong></div><div><b>Hinten</b><strong>'+dist('back')+'</strong></div><div><b>Z-Dienst</b><strong>'+dist('special')+'</strong></div><div><b>11–15 Uhr</b><strong>'+dist('early')+'</strong></div><div><b>15–18 Uhr</b><strong>'+dist('middle')+'</strong></div><div><b>ab 18 Uhr</b><strong>'+dist('late')+'</strong></div></div>':'')+'</section></section>';
 [['fairScope','scope'],['fairTeam','team'],['fairActivity','activity'],['fairSort','sort']].forEach(function(pair){var el=document.getElementById(pair[0]);if(el)el.onchange=function(){state[pair[1]]=el.value;state.open=null;render()}});
 var search=document.getElementById('fairSearch');if(search)search.onchange=function(){state.query=search.value;render()};
 document.getElementById('fairDirection').onclick=function(){state.dir=state.dir==='asc'?'desc':'asc';render()};
 host.querySelectorAll('[data-person]').forEach(function(row){var toggle=function(){state.open=state.open===row.dataset.person?null:row.dataset.person;render()};row.onclick=toggle;row.onkeydown=function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}}});
 document.getElementById('fairInfo').onclick=function(){state.info=!state.info;render()};document.getElementById('fairDistribution').onclick=function(){state.distribution=!state.distribution;render()};document.getElementById('fairCsv').onclick=csv;document.getElementById('fairPrint').onclick=function(){window.print()};
}
window.addEventListener('kc-v020-register-change',function(e){if(e.detail&&e.detail.id==='fairness')render()});window.addEventListener('kc-dp-data-loaded',function(){if(document.body.dataset.v020Register==='fairness')render()});
K.fairnessView={version:'0.20.0-b185',render:render,state:state,rows:dataRows};
})();