(function(){
'use strict';const K=window.KCDP=window.KCDP||{},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function open(){if(document.getElementById('hwDialog'))return;const api=K.handwritingProfiles,people=(K.people||[]).filter(p=>p.active&&api.allowed(p.personId)),d=document.createElement('dialog');d.id='hwDialog';d.style.cssText='width:min(920px,95vw);max-height:94vh;overflow:auto;padding:20px;border:1px solid #aaa;border-radius:12px';d.innerHTML=`<h2>Persönliche Handschrift anlernen</h2><p>Ziffern für Uhrzeiten lernen. Person wählen, Scan öffnen und jeweils <b>eine handgeschriebene Ziffer</b> mit dem Finger oder der Maus einrahmen. Gedruckte Vorgaben und Scanstreifen aussparen. Danach die passende Ziffer wählen. Buchstaben werden hier noch nicht gelernt.</p><label>Person <select id="hwPerson">${people.map(p=>`<option value="${esc(p.personId)}">${esc(p.name)}</option>`).join('')}</select></label><p><label>Scan (PNG/JPG) <input id="hwImage" type="file" accept="image/png,image/jpeg"></label> <label>Vorbereitetes Profil <input id="hwImport" type="file" accept="application/json,.json"></label></p><canvas id="hwCanvas" style="width:100%;touch-action:none;border:1px solid #ccc"></canvas><p><label>Ziffer <select id="hwDigit">${[...'0123456789'].map(x=>`<option>${x}</option>`).join('')}</select></label> <button id="hwTeach" style="min-height:44px">Ausschnitt lernen</button> <button id="hwUndo" style="min-height:44px">Letzte Probe entfernen</button></p><p id="hwStatus" role="status">Noch kein Profil geladen.</p><p>Die persönliche Erkennung liefert geprüfte Vorschläge, keine automatische Freigabe. Profile werden verschlüsselt auf diesem Gerät gespeichert. Für andere PCs Profil exportieren und dort importieren.</p><button id="hwSave" style="min-height:44px">Profil speichern</button> <button id="hwExport" style="min-height:44px">Profil exportieren</button> <button id="hwClose" style="min-height:44px">Schließen</button>`;document.body.append(d);d.showModal();const $=id=>d.querySelector('#'+id),canvas=$('hwCanvas'),ctx=canvas.getContext('2d');let image=null,selection=null,start=null,profile=null,dirty=false;const status=t=>$('hwStatus').textContent=t;const info=()=>status(profile?`${profile.samples.length} Proben · Ziffern: ${[...new Set(profile.samples.map(x=>x.label))].sort().join(', ')}${dirty?' · noch nicht gespeichert':''}`:'Kein Profil.');const draw=()=>{if(!image)return;ctx.drawImage(image,0,0,canvas.width,canvas.height);if(selection){ctx.strokeStyle='#cf172e';ctx.lineWidth=2;ctx.strokeRect(selection.x,selection.y,selection.w,selection.h)}};const load=async()=>{try{profile=await api.load($('hwPerson').value)||{schema:api.schema,personId:$('hwPerson').value,samples:[],createdAt:new Date().toISOString()};dirty=false;info()}catch(e){status(e.message)}};$('hwPerson').onchange=async()=>{if(dirty&&!confirm('Ungespeicherte Proben verwerfen?')){$('hwPerson').value=profile.personId;return}await load()};
const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{if(!image)return;start=point(e);canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!start)return;const end=point(e);selection={x:Math.max(0,Math.min(start.x,end.x)),y:Math.max(0,Math.min(start.y,end.y)),w:Math.abs(start.x-end.x),h:Math.abs(start.y-end.y)};draw()};canvas.onpointerup=()=>{start=null};
$('hwImage').onchange=async()=>{try{const file=$('hwImage').files[0];if(!file)return;image=await createImageBitmap(file);const scale=Math.min(1,1600/image.height);canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);selection=null;draw()}catch(e){status(e.message)}};
$('hwTeach').onclick=()=>{try{if(!image||!selection||selection.w<3||selection.h<8)throw Error('Bitte eine einzelne Ziffer einrahmen.');const original=document.createElement('canvas');original.width=canvas.width;original.height=canvas.height;original.getContext('2d').drawImage(image,0,0,original.width,original.height);profile.samples.push({label:$('hwDigit').value,...api.feature(api.crop(original,selection))});dirty=true;info()}catch(e){status(e.message)}};
$('hwUndo').onclick=()=>{profile?.samples.pop();dirty=true;info()};$('hwImport').onchange=async()=>{try{const f=$('hwImport').files[0];if(!f)return;if(f.size>1500000)throw Error('Profil zu groß.');const p=api.validate(JSON.parse(await f.text()));if(p.personId!==$('hwPerson').value)throw Error('Profil gehört zu einer anderen Person. Bitte zuerst die passende Person wählen.');if(dirty&&!confirm('Ungespeicherte Proben durch das importierte Profil ersetzen?'))return;profile=p;dirty=true;info()}catch(e){status(e.message)}};
$('hwSave').onclick=async()=>{try{await api.save(profile);dirty=false;status('Persönliches Ziffernprofil gespeichert. Künftige Foto-Erkennung berücksichtigt es bei sicherer Personenzuordnung. Jeder Vorschlag bleibt prüfpflichtig.')}catch(e){status(e.message)}};
$('hwExport').onclick=()=>{try{const p=api.validate(profile),u=URL.createObjectURL(new Blob([JSON.stringify(p)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='Handschrift-'+p.personId+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){status(e.message)}};const close=()=>{if(dirty&&!confirm('Ungespeicherte Proben verwerfen?'))return;image?.close?.();d.close();d.remove()};$('hwClose').onclick=close;d.oncancel=e=>{e.preventDefault();close()};load();}
function install(){const tools=document.querySelector('.photo-tools');if(tools&&!tools.querySelector('[data-handwriting]')){const b=document.createElement('button');b.className='secondary';b.dataset.handwriting='1';b.textContent='Handschriftprofil';b.onclick=open;tools.append(b)}}
K.handwritingProfileUi={open};new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();
})();
