(function(){
  'use strict';
  const K=window.KCDP=window.KCDP||{},KEY='kc.dp2.name-display.v1',defaults={mode:'full'};
  function load(){try{const old=JSON.parse(localStorage.getItem(KEY)||'{}'),mode=old.mode==='pseudo'||old.preferPseudo?'pseudo':old.mode==='first'?'first':'full';return{...defaults,...old,mode}}catch(_){return{...defaults}}}
  const state=load();
  function firstName(name){const value=String(name||'').trim();return value?value.split(/\s+/)[0]:''}
  function pseudo(p){const stored=String(p?.pseudoName||p?.pseudonym||p?.nickname||'').trim(),mapped=String(K.pseudoNamesByClearName?.[p?.name]||'').trim();return mapped||stored}
  function label(person,{allowPseudo=true}={}){const p=typeof person==='string'?K.person?.(person):person;if(!p)return'';if(allowPseudo&&state.mode==='pseudo')return pseudo(p)||firstName(p.name)||String(p.name||p.personId||'');return state.mode==='first'?firstName(p.name):String(p.name||p.personId||'')}
  function save(patch={}){if(['full','first','pseudo'].includes(patch.mode))state.mode=patch.mode;else if(patch.preferPseudo!=null)state.mode=patch.preferPseudo?'pseudo':state.mode==='pseudo'?'full':state.mode;state.preferPseudo=state.mode==='pseudo';try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){}decorate();K.dashboardPro?.render?.();K.fairnessView?.render?.();K.deviationsView?.render?.();K.hourMatrix?.render?.();return{...state}}
  function replaceName(host,p){if(!host||!p)return;const value=label(p),textNodes=[...host.childNodes].filter(node=>node.nodeType===Node.TEXT_NODE);if(textNodes.length!==1||textNodes[0].textContent!==value){textNodes.forEach(node=>node.remove());host.insertBefore(document.createTextNode(value),host.firstChild||null)}host.title=state.mode==='pseudo'&&pseudo(p)?`Pseudonym aus PC Manager · Klarname: ${p.name}`:state.mode==='pseudo'?`Kein Pseudonym hinterlegt · Anzeige: ${value}`:`Namensanzeige: ${state.mode==='first'?'Vorname':'Vor- und Nachname'}`}
  function decorate(){document.querySelectorAll('.person-row[data-person] .person-name').forEach(host=>replaceName(host,K.person?.(host.closest('.person-row').dataset.person)));document.querySelectorAll('[data-display-person]').forEach(host=>{const p=K.person?.(host.dataset.displayPerson),value=p&&label(p);if(p&&host.textContent!==value)host.textContent=value;host.title=p&&state.mode==='pseudo'&&pseudo(p)?`Pseudonym · Klarname: ${p.name}`:''});document.querySelectorAll('.dev-table-wrap tbody tr[data-dev-row] th>b').forEach(host=>{const id=host.closest('[data-dev-row]')?.dataset.devRow?.split('|')[0];replaceName(host,K.person?.(id))})}
  function settings(){const modal=document.getElementById('modal');if(!modal||!modal.querySelector('.settings-tabs [data-settings-tab="general"].active')||modal.querySelector('#nameDisplaySettings'))return;const summary=modal.querySelector('.workflow-grid')||modal.querySelector('.ai-summary');if(!summary)return;const box=document.createElement('section'),sample=(K.people||[]).find(p=>p.active!==false);box.id='nameDisplaySettings';box.className='name-display-settings';box.innerHTML=`<h3>Namensanzeige in Mitarbeiterlisten</h3><div class="name-display-options"><label><input type="radio" name="nameDisplayMode" value="full" ${state.mode==='full'?'checked':''}> Vor- und Nachname</label><label><input type="radio" name="nameDisplayMode" value="first" ${state.mode==='first'?'checked':''}> Nur Vorname</label><label><input type="radio" name="nameDisplayMode" value="pseudo" ${state.mode==='pseudo'?'checked':''}> Pseudonym</label></div><p><b>Vorschau:</b> <span id="nameDisplayPreview"></span><br><small>Für „Pseudonym“ wird ausschließlich <code>pseudoName</code> aus PC Manager verwendet. Fehlt es, erscheint der Vorname beziehungsweise Klarname.</small></p>`;summary.after(box);const preview=()=>{const out=document.getElementById('nameDisplayPreview');if(out)out.textContent=sample?`${label(sample)}${state.mode==='pseudo'&&pseudo(sample)?` · Klarname: ${sample.name}`:''}`:'Noch keine Personendaten'};box.querySelectorAll('[name="nameDisplayMode"]').forEach(x=>x.onchange=()=>{save({mode:x.value});preview()});preview()}
  let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate();settings()})}
  function install(){new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});schedule()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();K.personLabel=label;K.nameDisplay={version:'0.20.0-b173',state,label,firstName,pseudo,save,decorate};
})();