(function(){
  'use strict';
  const K=window.KCDP=window.KCDP||{},KEY='kcdp-person-sort-v1';let prefs={},scheduled=false,applying=false;
  const modes={standard:'Standard',name:'A–Z',start:'Beginn',morning:'Morgens',midday:'Mittags',evening:'Abends',front:'Vorne',back:'Hinten',flex:'Flexibel',special:'Z · Außerhalb',hours:'Stunden'};
  try{prefs=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){prefs={}}
  const context=()=>`${document.body.dataset.v020Register||K.state?.layer||'planned'}:${K.state?.view||'day'}`;
  const pref=()=>prefs[context()]||{mode:'standard',dir:1};
  function save(p){prefs[context()]=p;try{localStorage.setItem(KEY,JSON.stringify(prefs))}catch(_){}}
  function currentDay(){return K.days?.[Number(K.state?.dateIndex)||0]?.date||''}
  function personData(row,index){const id=row.dataset.person||row.querySelector('[data-person]')?.dataset.person||'',p=K.person?.(id)||{},found=(K.people||[]).findIndex(x=>x.personId===id),original=found<0?index:found,bars=[...row.querySelectorAll('.shift,.wish-bar')],lefts=bars.map(x=>parseFloat(x.style.left)).filter(Number.isFinite),earliest=lefts.length?Math.min(...lefts):1e9,hours=Number(String(row.querySelector('.hours-cell')?.textContent||'0').replace(',','.').split('/')[0])||0,date=currentDay(),layer=K.state?.layer||'planned',records=layer==='wish'?(K.wishes||[]).filter(x=>x.personId===id&&x.date===date&&x.status!=='deleted'):(K.shifts||[]).filter(x=>x.personId===id&&x.date===date&&x.layer==='planned'&&!['deleted','cancelled'].includes(x.status)),starts=records.map(x=>Number(x.start)).filter(Number.isFinite),start=starts.length?Math.min(...starts):earliest,overlap=(a,b)=>records.some(x=>Number(x.start)<b&&Number(x.end)>a),zones=new Set(records.map(x=>x.wishZone||x.zone));return{id,index,original,name:String(p.name||row.querySelector('.person-name')?.textContent||'').trim(),hours,start,morning:overlap(0,12),midday:overlap(12,17),evening:overlap(17,30),front:zones.has('V')||zones.has('front'),back:zones.has('H')||zones.has('back'),flex:zones.has('B')||zones.has('neutral'),special:zones.has('Z')||zones.has('special')}}
  function compare(a,b,p){const d=p.dir||1,txt=(x,y)=>x.localeCompare(y,'de',{sensitivity:'base'}),bool=k=>(Number(b[k])-Number(a[k]))||a.start-b.start||txt(a.name,b.name);let v=0;if(p.mode==='name')v=txt(a.name,b.name);else if(p.mode==='start')v=a.start-b.start||txt(a.name,b.name);else if(['morning','midday','evening','front','back','flex','special'].includes(p.mode))v=bool(p.mode);else if(p.mode==='hours')v=a.hours-b.hours||txt(a.name,b.name);else v=(a.original??a.index)-(b.original??b.index);return v*d}
  function groups(grid){const rows=[...grid.querySelectorAll(':scope>.person-row')];return rows.map((row,index)=>{const nodes=[row];let n=row.nextElementSibling;while(n?.classList.contains('expanded-detail')){nodes.push(n);n=n.nextElementSibling}return{row,nodes,data:personData(row,index)}})}
  function sortDay(p){const grid=document.querySelector('.planner-grid');if(!grid)return;const list=groups(grid),sorted=[...list].sort((a,b)=>compare(a.data,b.data,p)),anchor=grid.querySelector('.matrix')||null;if(sorted.every((x,i)=>x===list[i]))return;applying=true;for(const g of sorted)for(const node of g.nodes)grid.insertBefore(node,anchor);applying=false}
  function sortSummary(p){const body=document.querySelector('.summary-table tbody');if(!body)return;const rows=[...body.rows],items=rows.map((row,index)=>({row,data:{index,name:String(row.cells[0]?.textContent||'').trim(),hours:Number(String(row.cells[1]?.textContent||'0').replace(',','.').split('/')[0])||0,start:1e9,morning:false,midday:false,evening:false,front:false,back:false,flex:false,special:false}})),sorted=items.sort((a,b)=>compare(a.data,b.data,p));if(sorted.every((x,i)=>x.row===rows[i]))return;applying=true;sorted.forEach(x=>body.appendChild(x.row));applying=false}
  function apply(){const p=pref();sortDay(p);sortSummary(p)}
  function close(){document.getElementById('personSortBackdrop')?.remove()}
  function choose(mode){const p={...pref(),mode};save(p);close();apply();install()}
  function open(){close();const p=pref(),back=document.createElement('div');back.id='personSortBackdrop';back.className='person-sort-backdrop';back.innerHTML=`<section class="person-sort-panel" role="dialog" aria-modal="true" aria-labelledby="personSortTitle"><header class="person-sort-head"><h2 id="personSortTitle">Mitarbeiter sortieren</h2><button class="person-sort-close" aria-label="Schließen">×</button></header><div class="person-sort-body"><div class="person-sort-group"><h3>Allgemein</h3>${option('standard','Ursprüngliche Reihenfolge','Wie in der Mitgliederliste')}${option('name','Name','Alphabetisch')}${option('start','Dienstbeginn','Frühester oder spätester Beginn')}${option('hours','Stunden','Wenige oder viele Stunden')}</div><div class="person-sort-group"><h3>Tageszeit</h3>${option('morning','Morgens','Einsatz vor 12 Uhr')}${option('midday','Mittags','Einsatz zwischen 12 und 17 Uhr')}${option('evening','Abends','Einsatz ab 17 Uhr')}</div><div class="person-sort-group"><h3>Bereich</h3>${option('front','Vorne (V)','Vorne zuerst')}${option('back','Hinten (H)','Hinten zuerst')}${option('flex','Flexibel (B)','Beides/Flexibel zuerst')}${option('special','Außerhalb (Z)','Z-Sonderdienste außerhalb zuerst')}</div></div><footer class="person-sort-actions"><button id="personSortAsc" class="${p.dir===1?'active':''}">↑ Aufsteigend</button><button id="personSortDesc" class="${p.dir===-1?'active':''}">↓ Absteigend</button></footer></section>`;document.body.appendChild(back);back.onclick=e=>{if(e.target===back)close()};back.querySelector('.person-sort-close').onclick=close;back.querySelectorAll('[data-sort-mode]').forEach(b=>b.onclick=()=>choose(b.dataset.sortMode));back.querySelector('#personSortAsc').onclick=()=>{save({...pref(),dir:1});close();apply();install()};back.querySelector('#personSortDesc').onclick=()=>{save({...pref(),dir:-1});close();apply();install()};setTimeout(()=>back.querySelector('.person-sort-option.active,.person-sort-option')?.focus(),0)}
  function option(mode,label,sub){return `<button class="person-sort-option ${pref().mode===mode?'active':''}" data-sort-mode="${mode}">${label}<small>${sub}</small></button>`}
  function install(){const host=document.querySelector('.time-header .sticky-name')||document.querySelector('.summary-table thead th:first-child');if(!host)return;let b=host.querySelector('.person-sort-trigger'),created=false;if(!b){b=document.createElement('button');b.type='button';b.className='person-sort-trigger';b.onclick=e=>{e.stopPropagation();open()};host.appendChild(b);created=true}const p=pref(),label=`↕ ${modes[p.mode]||'Sortieren'}`;if(b.textContent!==label)b.textContent=label;b.title=`Mitarbeiter sortieren: ${modes[p.mode]||'Standard'} · ${p.dir===1?'aufsteigend':'absteigend'}`;b.setAttribute('aria-label',b.title);if(created)apply()}
  function schedule(){if(applying||scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;install()})}
  addEventListener('keydown',e=>{if(e.key==='Escape')close()});new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});install();K.personSort={open,apply,prefs};
})();
