(function(){
  'use strict';
  const KEY='kcdp-device-view-v1',defaults={focus:false,dense:false,kpis:false,context:false,plan:false,lowerGap:0,lowerOrder:'matrix-first'};
  let state=defaults;
  try{state={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(_){state={...defaults}}
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_){}};
  function apply(){document.body.classList.toggle('kc-focus-mode',!!state.focus);document.body.classList.toggle('kc-dense-planning',!!state.dense);document.body.classList.toggle('kc-kpis-collapsed',!!state.kpis);document.body.classList.toggle('kc-context-collapsed',!!state.context);document.body.classList.toggle('kc-plan-collapsed',!!state.plan);const f=document.getElementById('planningFocusBtn');if(f){f.setAttribute('aria-pressed',String(!!state.focus));if(f.textContent!=='⛶')f.textContent='⛶';f.title=state.focus?'Arbeitsbildschirm verlassen (Esc)':'Planung maximieren'}const d=document.getElementById('planningDenseBtn');if(d){d.setAttribute('aria-pressed',String(!!state.dense));d.title=state.dense?'Normale Zeilenhöhe wiederherstellen':'Planungszeilen verdichten';d.setAttribute('aria-label',d.title)}for(const [id,key] of [['focusKpiBtn','kpis'],['focusContextBtn','context'],['focusPlanBtn','plan']]){const b=document.getElementById(id);if(b)b.setAttribute('aria-pressed',String(!!state[key]))}}
  function toggle(key){state[key]=!state[key];save();apply()}
  function installLowerLayout(){
    const grid=document.querySelector('.planner-grid');if(!grid)return;
    const children=()=>[...grid.children],matrix=children().find(x=>x.classList.contains('matrix')),standby=children().find(x=>x.classList.contains('standby-section'));
    if(!matrix)return;grid.classList.add('kc-lower-layout');
    let spacer=children().find(x=>x.classList.contains('planner-lower-spacer')),handle=children().find(x=>x.classList.contains('planner-lower-separator'));
    if(!spacer){spacer=document.createElement('div');spacer.className='planner-lower-spacer';grid.insertBefore(spacer,matrix)}
    if(!handle){handle=document.createElement('div');handle.className='planner-lower-separator';handle.title='Ziehen: Besetzungs- und Bereitschaftsblock nach oben oder unten verschieben';handle.innerHTML='<span class="lower-grip" aria-hidden="true">⋮⋮⋮</span><button type="button" class="lower-swap" title="Besetzungsmatrix und Bereitschaft tauschen" aria-label="Besetzungsmatrix und Bereitschaft tauschen"><b>B</b><i>⇅</i></button>';grid.insertBefore(handle,matrix)}
    const arrange=()=>{const swap=handle.querySelector('.lower-swap');if(!standby){if(handle.nextElementSibling!==matrix)handle.after(matrix);if(swap){swap.disabled=true;swap.title='Bereitschaft ist in dieser Ansicht nicht vorhanden';swap.setAttribute('aria-pressed','false')}return}if(swap){swap.disabled=false;swap.title='Besetzungsmatrix und Bereitschaft tauschen'}const first=state.lowerOrder==='standby-first'?standby:matrix,second=first===standby?matrix:standby;if(handle.nextElementSibling!==first)handle.after(first);if(first.nextElementSibling!==second)first.after(second);swap?.setAttribute('aria-pressed',String(state.lowerOrder==='standby-first'))};
    const applyGap=()=>{const gap=Number(state.lowerGap)||0;spacer.style.height=`${Math.max(0,gap)}px`;spacer.style.marginTop=`${Math.min(0,gap)}px`};applyGap();arrange();
    const swap=handle.querySelector('.lower-swap');swap.onclick=e=>{e.stopPropagation();if(!standby)return;state.lowerOrder=state.lowerOrder==='standby-first'?'matrix-first':'standby-first';save();arrange()};
    handle.onpointerdown=e=>{if(e.target.closest('button'))return;e.preventDefault();const start=e.clientY,base=Number(state.lowerGap)||0;handle.setPointerCapture?.(e.pointerId);handle.classList.add('dragging');const move=ev=>{state.lowerGap=Math.max(-420,Math.min(420,base+ev.clientY-start));applyGap()};const up=()=>{removeEventListener('pointermove',move);removeEventListener('pointerup',up);handle.classList.remove('dragging');save()};addEventListener('pointermove',move);addEventListener('pointerup',up,{once:true})};
    handle.ondblclick=e=>{if(e.target.closest('button'))return;state.lowerGap=0;applyGap();save()};  }  function install(){const exit=document.getElementById('exitBtn');if(exit&&!document.getElementById('planningFocusBtn')){const b=document.createElement('button');b.type='button';b.id='planningFocusBtn';b.className='icon-btn kc-focus-btn';b.setAttribute('aria-label','Planung maximieren');b.onclick=()=>toggle('focus');exit.before(b)}const focus=document.getElementById('planningFocusBtn');if(focus&&!document.getElementById('planningDenseBtn')){const b=document.createElement('button');b.type='button';b.id='planningDenseBtn';b.className='icon-btn kc-dense-btn';b.textContent='⇵';b.setAttribute('aria-label','Planungszeilen verdichten');b.onclick=()=>toggle('dense');focus.before(b)}const row=document.querySelector('.plan-control-row');if(row&&!document.getElementById('focusViewControls')){const box=document.createElement('span');box.id='focusViewControls';box.className='kc-view-controls';box.setAttribute('aria-label','Bereiche ein- und ausblenden');box.innerHTML='<button type="button" class="tool-btn" id="focusKpiBtn" title="Kennzahlen ein-/ausblenden" aria-label="Kennzahlen ein-/ausblenden">▦</button><button type="button" class="tool-btn" id="focusContextBtn" title="Tageskopf und Hinweise ein-/ausblenden" aria-label="Tageskopf und Hinweise ein-/ausblenden">ⓘ</button><button type="button" class="tool-btn" id="focusPlanBtn" title="Planungsbereich ein-/ausblenden" aria-label="Planungsbereich ein-/ausblenden">▤</button>';row.append(box);box.querySelector('#focusKpiBtn').onclick=()=>toggle('kpis');box.querySelector('#focusContextBtn').onclick=()=>toggle('context');box.querySelector('#focusPlanBtn').onclick=()=>toggle('plan')}installLowerLayout();apply()}
  function height(){document.body.classList.toggle('kc-low-height',innerHeight<=850)}
  addEventListener('resize',height,{passive:true});addEventListener('keydown',e=>{if(e.key==='Escape'&&state.focus&&!document.querySelector('.modal-backdrop:not(.hidden)')){state.focus=false;save();apply()}});
  new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});height();install();
})();
