(function(){
  const K=window.KCDP=window.KCDP||{};
  const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const ADMIN_ROLES=new Set(['planner','duty_manager','admin']);
  const templates={
    update:{label:'Neues Update',title:'KC DP2 – Neues Update',body:'Eine neue KC-DP2-Version ist verfügbar. Bitte öffnen und aktualisieren.',route:'update'},
    install:{label:'Bitte installieren',title:'KC DP2 – Bitte installieren',body:'KC DP2 ist für Sie bereit. Bitte antippen und auf diesem Gerät installieren.',route:'install'},
    info:{label:'Information',title:'KC DP2 – Information',body:'Neue Information aus der Dienstplanung.',route:'notifications'},
    warning:{label:'Achtung',title:'KC DP2 – Achtung',body:'Bitte beachten Sie diese wichtige Mitteilung.',route:'notifications'},
    plan:{label:'Dienstplan geändert',title:'KC DP2 – Dienstplan geändert',body:'Ihr Dienstplan wurde geändert. Bitte prüfen Sie die aktuellen Zeiten.',route:'personal_plan'}
  };
  let installPrompt=null,settingsWindowUntil=0;
  function allowed(){return ADMIN_ROLES.has(String(K.currentUser?.role||''));}
  function activePeople(){return (K.people||[]).filter(p=>p&&p.active!==false&&p.personId).slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'de'));}
  function openShell(html){let host=document.getElementById('kcPushCenterOverlay');if(!host){host=document.createElement('div');host.id='kcPushCenterOverlay';host.className='kc-install-overlay';document.body.appendChild(host)}host.innerHTML=`<div class="kc-install-card" style="width:min(900px,97vw);max-height:92vh;overflow:auto">${html}</div>`;host.onclick=e=>{if(e.target===host)close()};return host;}
  function close(){document.getElementById('kcPushCenterOverlay')?.remove()}
  function personList(){return activePeople().map(p=>`<label class="kc-push-person"><input type="checkbox" data-push-person value="${esc(p.personId)}"><span><b>${esc(p.name||p.personId)}</b>${p.role?` · ${esc(p.role)}`:''}</span></label>`).join('')||'<p>Keine aktiven Personen gefunden.</p>'}
  function render(){
    if(!allowed())return alert('Das Push-Center ist nur für Planung, Dienstleitung oder Admin freigegeben.');
    const tplButtons=Object.entries(templates).map(([k,t])=>`<button type="button" data-push-template="${k}">${esc(t.label)}</button>`).join('');
    const host=openShell(`<section class="kc-push-center"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><div><h2>🔔 Push-Center</h2><p style="margin:5px 0 0">Nachrichten vorbereiten, Empfänger wählen, prüfen und versenden.</p></div><button type="button" id="kcPushClose" aria-label="Schließen">✕</button></div><div class="kc-push-card"><h3>Vorlagen</h3><div class="kc-push-template-row" style="margin-top:10px">${tplButtons}</div></div><div class="kc-push-grid"><div class="kc-push-card"><label>Anlass<select id="kcPushType"><option value="info">Information</option><option value="update">Neues Update</option><option value="install">Installation</option><option value="warning">Warnung</option><option value="plan">Dienstplan geändert</option><option value="custom">Freie Nachricht</option></select></label><label>Titel<input id="kcPushTitle" maxlength="90"></label><label>Nachricht<textarea id="kcPushBody" maxlength="500"></textarea></label><label>Ziel beim Antippen<select id="kcPushRoute"><option value="notifications">Meldungen</option><option value="install">Installationsseite</option><option value="update">Update</option><option value="personal_plan">Persönlicher Dienstplan</option><option value="home">KC DP2 Start</option></select></label></div><div class="kc-push-card"><label>Empfänger<select id="kcPushAudience"><option value="all">Alle aktiven Personen</option><option value="selected">Personen auswählen</option></select></label><div id="kcPushPeople" class="kc-push-people" hidden>${personList()}</div><p id="kcPushRecipientCount"></p><small>Der Server sendet nur an Geräte, die Push bereits aktiviert haben. Personen ohne aktive Subscription werden nicht zugestellt.</small></div></div><div class="kc-push-preview" id="kcPushPreview"></div><div class="kc-push-stats" id="kcPushStats"><div class="kc-push-stat"><strong>–</strong>Gesendet</div><div class="kc-push-stat"><strong>–</strong>Angezeigt</div><div class="kc-push-stat"><strong>–</strong>Geöffnet</div><div class="kc-push-stat"><strong>–</strong>Fehler</div></div><div class="kc-push-actions"><button type="button" class="secondary" id="kcPushRefresh">Status aktualisieren</button><button type="button" class="secondary" id="kcPushClose2">Abbrechen</button><button type="button" class="primary" id="kcPushSend">Vorschau prüfen & senden</button></div></section>`);
    const $=id=>host.querySelector('#'+id);
    function applyTemplate(key){const t=templates[key]||templates.info;$('kcPushType').value=key;$('kcPushTitle').value=t.title;$('kcPushBody').value=t.body;$('kcPushRoute').value=t.route;preview()}
    function ids(){if($('kcPushAudience').value==='all')return activePeople().map(p=>String(p.personId));return [...host.querySelectorAll('[data-push-person]:checked')].map(x=>x.value)}
    function preview(){const count=ids().length,title=$('kcPushTitle').value.trim(),body=$('kcPushBody').value.trim(),route=$('kcPushRoute').value;$('kcPushRecipientCount').textContent=`${count} Empfänger ausgewählt.`;$('kcPushPreview').innerHTML=`<b>${esc(title||'Kein Titel')}</b><span>${esc(body||'Keine Nachricht')}</span><small style="display:block;margin-top:7px">Beim Antippen: ${route==='install'?'KC DP2 installieren':route==='update'?'Update öffnen':route==='personal_plan'?'persönlicher Dienstplan':route==='notifications'?'Meldungen':'KC DP2 Start'}</small>`}
    async function refreshStats(){try{const d=await K.pushAdapter.deliveryStatus(),rows=d.deliveries||d.items||d.results||[];let sent=Number(d.sent||0),displayed=Number(d.displayed||0),opened=Number(d.opened||0),errors=Number(d.errors||0);if(Array.isArray(rows)&&rows.length){sent=rows.filter(x=>x.sent_at||x.status==='sent').length;displayed=rows.filter(x=>x.displayed_at).length;opened=rows.filter(x=>x.opened_at).length;errors=rows.filter(x=>x.error||x.status==='error').length}const vals=[sent,displayed,opened,errors];host.querySelectorAll('#kcPushStats strong').forEach((el,i)=>el.textContent=String(vals[i]??'–'));}catch(e){host.querySelector('#kcPushStats').title=e.message}}
    async function send(){const recipients=ids(),title=$('kcPushTitle').value.trim(),body=$('kcPushBody').value.trim(),route=$('kcPushRoute').value;if(!recipients.length)return alert('Bitte mindestens einen Empfänger auswählen.');if(!title||!body)return alert('Bitte Titel und Nachricht ausfüllen.');const names=activePeople().filter(p=>recipients.includes(String(p.personId))).map(p=>p.name||p.personId);const summary=recipients.length>8?`${recipients.length} Personen`:names.join(', ');if(!confirm(`Push wirklich senden?\n\n${title}\n${body}\n\nEmpfänger: ${summary}`))return;const btn=$('kcPushSend');btn.disabled=true;btn.textContent='Sende …';try{const id=`ADMIN-${Date.now()}`,payload={id,title,body,data:{route,kind:$('kcPushType').value,install:route==='install'}};const out=await K.pushAdapter.sendMany(payload,recipients);alert(`Push-Versand abgeschlossen.\nAngefordert: ${recipients.length}\nServer gesendet: ${out.result?.sent??'siehe Status'}\nFehler: ${out.result?.failed??out.result?.errors??0}`);await refreshStats();}catch(e){alert('Push nicht gesendet: '+e.message)}finally{btn.disabled=false;btn.textContent='Vorschau prüfen & senden'}}
    host.querySelectorAll('[data-push-template]').forEach(b=>b.onclick=()=>applyTemplate(b.dataset.pushTemplate));$('kcPushClose').onclick=$('kcPushClose2').onclick=close;$('kcPushAudience').onchange=()=>{$('kcPushPeople').hidden=$('kcPushAudience').value!=='selected';preview()};host.querySelectorAll('[data-push-person]').forEach(x=>x.onchange=preview);['kcPushTitle','kcPushBody','kcPushRoute'].forEach(id=>$(id).addEventListener('input',preview));$('kcPushType').onchange=()=>{const v=$('kcPushType').value;if(templates[v])applyTemplate(v);else preview()};$('kcPushSend').onclick=send;$('kcPushRefresh').onclick=refreshStats;applyTemplate('info');refreshStats();
  }
  function injectAdminEntry(){if(!allowed()||Date.now()>settingsWindowUntil)return;const modal=document.getElementById('modal'),back=document.getElementById('modalBackdrop');if(!modal||back?.classList.contains('hidden')||document.getElementById('kcPushAdminEntry'))return;const btn=document.createElement('button');btn.id='kcPushAdminEntry';btn.className='kc-push-admin-entry';btn.type='button';btn.textContent='🔔 Push-Center – Nachrichten & Installation';btn.onclick=render;modal.appendChild(btn)}
  function installSettingsHook(){document.getElementById('settingsBtn')?.addEventListener('click',()=>{settingsWindowUntil=Date.now()+1500;setTimeout(injectAdminEntry,50);setTimeout(injectAdminEntry,250)});new MutationObserver(()=>injectAdminEntry()).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});}
  function installed(){return window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true}
  function installRequested(){const q=new URLSearchParams(location.search);return q.get('install')==='1'||q.get('route')==='install'}
  function showInstallCard(){if(installed())return;let box=document.getElementById('kcInstallInvite');if(box)return;box=document.createElement('div');box.id='kcInstallInvite';box.className='kc-install-overlay';box.innerHTML='<div class="kc-install-card"><h2>KC DP2 installieren</h2><p>Installieren Sie KC DP2 auf diesem Gerät. Danach startet der Dienstplan wie eine normale App über ein eigenes Symbol.</p><p id="kcInstallHint"></p><div class="actions"><button type="button" id="kcInstallLater">Später</button><button type="button" class="primary" id="kcInstallNow">KC DP2 installieren</button></div></div>';document.body.appendChild(box);box.querySelector('#kcInstallLater').onclick=()=>box.remove();box.querySelector('#kcInstallNow').onclick=async()=>{const hint=box.querySelector('#kcInstallHint');if(installPrompt){installPrompt.prompt();const choice=await installPrompt.userChoice;hint.textContent=choice.outcome==='accepted'?'Installation bestätigt. KC DP2 kann gleich über das App-Symbol gestartet werden.':'Installation wurde nicht durchgeführt.';if(choice.outcome==='accepted')setTimeout(()=>box.remove(),1200);installPrompt=null;}else{hint.textContent='Falls kein Installationsfenster erscheint: Im Browser-Menü „App installieren“ oder „Zum Startbildschirm hinzufügen“ wählen.'}}}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(installRequested())showInstallCard()});
  window.addEventListener('appinstalled',()=>document.getElementById('kcInstallInvite')?.remove());
  document.addEventListener('DOMContentLoaded',()=>{installSettingsHook();if(installRequested())setTimeout(showInstallCard,300)});
  K.pushCenter={open:render,allowed,showInstallCard,templates};
})();