(function(){
'use strict';const K=window.KCDP,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),tm=h=>String(Math.floor(h)).padStart(2,'0')+':'+String(Math.round(h%1*60)).padStart(2,'0'),z=w=>({front:'vorne',back:'hinten',flex:'beides',special:'Sonderfunktion Z'}[K.wishDemand.zone(w)]);
function report(w,options){const r=K.wishDemand.evaluate(w,options),display=[];for(const part of r.parts){const last=display.at(-1),key=JSON.stringify([part.req,part.counts,part.status,part.people.map(p=>p.id)]);if(last&&last.end===part.start&&last.key===key)last.end=part.end;else display.push({...part,key});}return `<article class="wd-report"><h3>${esc(w.date)} · ${tm(w.start)}–${tm(w.end)} (${z(w)})</h3><b>${r.rating}</b><p>Vergleich mit der Besetzungsmatrix und vorhandenen Wunschzeiten. Noch keine feste Einteilung.</p>${display.map(p=>`<div class="wd-part"><b>${tm(p.start)}–${tm(p.end)}</b> · ${p.status==='gap'?'Hier wird noch Hilfe benötigt':p.status==='full'?'Bereits ausreichend Wünsche':p.status==='over'?'Bereits mehr Wünsche als benötigt':'Keine eindeutige Bereichsbewertung'}<br><small>Soll: ${p.req?.front??'–'} V / ${p.req?.back??'–'} H · Wünsche: ${p.counts.front} V / ${p.counts.back} H${p.counts.flex?' + '+p.counts.flex+' flexibel':''} · Mit dir: ${p.after.front} V / ${p.after.back} H${p.after.flex?' + '+p.after.flex+' flexibel':''}</small></div>`).join('')}<details><summary>Wer ist bereits eingetragen?</summary>${[...new Map(r.parts.flatMap(x=>x.people).map(x=>[x.id||JSON.stringify(x),x])).values()].map(p=>`<p>${esc(K.person(p.personId)?.pseudoName||K.person(p.personId)?.name||p.personId)} · ${z(p)} · ${tm(p.start)}–${tm(p.end)}</p>`).join('')||'<p>Noch keine anderen Wunschzeiten in diesem Zeitraum.</p>'}</details></article>`;}
function live(list,dates){const prefs=list.filter(x=>x.wishType==='preferred'&&Number.isFinite(x.start)&&Number.isFinite(x.end)&&x.start<x.end);return prefs.length?`<section class="wd-live"><b>Besetzungsprüfung: ${[...new Set(prefs.map(w=>K.wishDemand.evaluate(w,{draft:list,replaceDates:dates}).rating))].join(" · ")}</b><details><summary>Besetzung und vorhandene Wünsche ansehen</summary>${prefs.map(w=>report(w,{draft:list,replaceDates:dates})).join('')}</details></section>`:'';}
function confirm(list,dates,personId){
 const prefs=list.filter(x=>x.wishType==='preferred');if(!prefs.length)return Promise.resolve(true);
 return new Promise(resolve=>{const box=document.createElement('div');box.className='wd-overlay';box.id='wishDemandDialog';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','Wunschzeiten prüfen');
 const options={draft:list,replaceDates:dates,personId};let selected=null;
 const close=answer=>{box.remove();resolve(answer)};
 const render=()=>{const full=prefs.some(w=>K.wishDemand.evaluate(w,options).hasFull);box.innerHTML=`<section class="wd-dialog"><h2>So passen deine Wunschzeiten</h2>${prefs.map(w=>report(w,options)).join('')}<div id="wdAlternatives"></div><div class="wd-actions"><button type="button" id="wdAccept">${full?'Trotzdem eintragen':'Wunsch eintragen'}</button><button type="button" id="wdSearch">${full?'Bessere Zeit suchen':'Weitere passende Zeiten'}</button><button type="button" id="wdOther">Andere Zeit wählen</button><button type="button" id="wdCancel">Abbrechen</button></div></section>`;box.querySelector('#wdAccept').onclick=()=>close(true);box.querySelector('#wdOther').onclick=()=>close(false);box.querySelector('#wdCancel').onclick=()=>close(false);box.querySelector('#wdSearch').onclick=()=>{
 const alternatives=prefs.flatMap(w=>K.wishDemand.alternatives(w,options).map(a=>({w,a})));const target=box.querySelector('#wdAlternatives');target.innerHTML='<h3>Passende Alternativen</h3>'+(alternatives.map(({a},i)=>`<button type="button" data-wd-alternative="${i}">${esc(a.date)} · ${tm(a.start)}–${tm(a.end)} · ${z(a)}<br>${a.rating} · mindestens ${a.missing} Person(en) fehlen</button>`).join('')||'<p>Keine passende Alternative innerhalb deiner Kannzeiten gefunden. Du kannst den ursprünglichen Wunsch trotzdem eintragen.</p>');target.querySelectorAll('[data-wd-alternative]').forEach(b=>b.onclick=()=>{
 const {w,a}=alternatives[Number(b.dataset.wdAlternative)],fresh=K.wishDemand.alternatives(w,options).some(x=>x.date===a.date&&x.start===a.start&&x.end===a.end);if(!fresh){target.innerHTML='<p>Der Datenstand hat sich geändert. Bitte erneut suchen.</p>';return;}
 const index=list.indexOf(w);if(!dates.includes(a.date)){dates.push(a.date);list.push(...K.mobileWishMatrix.rows(personId,a.date));}
 list[index]={...w,id:a.date===w.date?w.id:'',date:a.date,start:a.start,end:a.end};prefs.splice(prefs.indexOf(w),1,list[index]);render();
 });};};render();document.body.appendChild(box);box.querySelector('#wdAccept').focus();
 });
}
K.wishDemandUi={live,confirm,report};
})();
