(function(){
'use strict';
const K=window.KCDP=window.KCDP||{},$=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const fmtDate=iso=>new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(iso+'T12:00:00'));
const fmtTime=h=>`${String(Math.floor(h)).padStart(2,'0')}:${String(Math.round((h%1)*60)).padStart(2,'0')}`;
const dayVisualClass=d=>{const wd=new Date(d.date+'T12:00:00').getDay();return [d.type==='prep'?'day-prep':d.type==='after'?'day-after':'',wd===6?'day-saturday':wd===0?'day-sunday':''].filter(Boolean).join(' ')};
const positive=w=>!['unavailable','deleted','cancelled'].includes(w.wishType)&&w.status!=='deleted';
let personId=null,scope='week',anchor=null,pendingShell=null,shellRetry=0;
function shell(html){const root=$('kcdpUxRoot');if(!root){pendingShell=html;if(shellRetry<20){shellRetry++;setTimeout(()=>{const next=pendingShell;if(next)shell(next)},50);return false}pendingShell=null;shellRetry=0;window.dispatchEvent(new CustomEvent('kc-dp-diagnostic-error',{detail:{message:'Mitarbeiteransicht konnte nach Wartezeit nicht initialisiert werden.',code:'member.view.root_timeout',severity:'warning',context:{module:'wish-sprint',phase:'render'}}}));return false}pendingShell=null;shellRetry=0;root.innerHTML=`<main class="ux-shell ux-wish-sprint">${html}</main>`;return true;}
function visibleDates(){const days=K.days||[];if(!anchor)anchor=days[0]?.date;if(scope==='all')return days.map(d=>d.date);const i=Math.max(0,days.findIndex(d=>d.date===anchor));if(scope==='day')return days[i]?[days[i].date]:[];const start=Math.floor(i/7)*7;return days.slice(start,start+7).map(d=>d.date);}
function move(delta){const days=K.days||[],i=Math.max(0,days.findIndex(d=>d.date===anchor)),step=scope==='week'?7:1;anchor=days[Math.max(0,Math.min(days.length-1,i+delta*step))]?.date||anchor;detail();}
function grouped(){const dates=new Set(visibleDates()),rows=(K.wishes||[]).filter(w=>w.personId===personId&&positive(w)&&dates.has(w.date)).sort((a,b)=>a.date.localeCompare(b.date)||a.start-b.start),map=new Map();for(const w of rows){if(!map.has(w.date))map.set(w.date,[]);map.get(w.date).push(w)}return map;}
function detail(){const p=K.person(personId),days=K.days||[],groups=grouped(),dates=visibleDates();if(!shell(`<div class="ux-pagebar"><button class="ux-btn secondary" id="wsBack">←</button><div><h1>${esc(p?.name||'Kollege')}</h1><p>Zeitangaben vor der Übernahme vollständig prüfen.</p></div></div><section class="ux-card ws-controls"><div class="ux-field"><label>Zeitraum</label><select id="wsScope"><option value="day" ${scope==='day'?'selected':''}>Ein Tag</option><option value="week" ${scope==='week'?'selected':''}>Eine Woche</option><option value="all" ${scope==='all'?'selected':''}>Gesamter Zeitraum</option></select></div><button class="ux-btn secondary" id="wsPrev" ${scope==='all'?'disabled':''}>← Zurück</button><div class="ws-anchor"><select id="wsDay">${days.map(d=>`<option value="${d.date}" ${d.date===anchor?'selected':''}>${fmtDate(d.date)}</option>`).join('')}</select></div><button class="ux-btn secondary" id="wsNext" ${scope==='all'?'disabled':''}>Weiter →</button></section><section class="ux-card ws-table"><div class="ws-table-head"><b>Tag</b><b>Zeitfenster</b><b>Auswahl</b></div>${dates.map(date=>{const rows=groups.get(date)||[];return `<div class="ws-day"><div class="ws-date"><b>${fmtDate(date)}</b><label><input type="checkbox" data-day="${date}" ${rows.length?'checked':'disabled'}> alle Zeiten</label></div><div class="ws-slots">${rows.length?rows.map(w=>`<label class="ws-slot"><span><b>${fmtTime(w.start)}–${fmtTime(w.end)}</b><small>${w.start<12?'Vormittag':w.start<18?'Nachmittag':'Abend'} · ${esc(K.wishTypeLabel?.(w.wishType)||w.wishType)}</small></span><input type="checkbox" data-copywish="${w.id}" data-date="${date}" checked></label>`).join(''):'<span class="ws-empty">Keine Zeit angegeben</span>'}</div></div>`}).join('')}</section><div class="ws-sticky"><span id="wsCount"></span><button class="ux-btn primary" id="wsCopy">Ausgewählte Zeiten übernehmen</button></div>`))return;$('wsBack').onclick=()=>K.wishSprint.search();$('wsScope').onchange=e=>{scope=e.target.value;detail()};$('wsDay').onchange=e=>{anchor=e.target.value;detail()};$('wsPrev').onclick=()=>move(-1);$('wsNext').onclick=()=>move(1);document.querySelectorAll('[data-day]').forEach(x=>x.onchange=()=>document.querySelectorAll(`[data-copywish][data-date="${x.dataset.day}"]`).forEach(c=>c.checked=x.checked));const count=()=>{$('wsCount').textContent=`${document.querySelectorAll('[data-copywish]:checked').length} Zeitfenster ausgewählt`};document.querySelectorAll('[data-copywish],[data-day]').forEach(x=>x.addEventListener('change',count));count();$('wsCopy').onclick=()=>{const ids=[...document.querySelectorAll('[data-copywish]:checked')].map(x=>x.dataset.copywish);if(!ids.length)return alert('Bitte mindestens ein Zeitfenster auswählen.');K.wishSprint.copy(personId,ids)};}
function search(){if(!shell(`<div class="ux-pagebar"><button class="ux-btn secondary" id="wsHome">←</button><h1>Kollegen suchen</h1></div><section class="ux-card"><p>Kollegen auswählen und deren Zeiten zunächst nach Tag, Woche oder Gesamtzeitraum ansehen.</p><div class="ux-searchbox"><input id="wsQuery" type="search" placeholder="Name des Kollegen"><button class="ux-btn primary" id="wsFind">Suchen</button></div><div id="wsResults"></div></section>`))return;$('wsHome').onclick=()=>K.roleUx?.showRoleHome?.();const run=()=>{const q=$('wsQuery').value.trim().toLowerCase(),list=(K.people||[]).filter(p=>p.active&&p.personType==='member'&&p.personId!==K.currentUser?.personId&&(!q||p.name.toLowerCase().includes(q))).slice(0,20);$('wsResults').innerHTML=list.map(p=>`<button class="ux-person-result" data-person="${p.personId}"><b>${esc(p.name)}</b><small>${K.wishes.filter(w=>w.personId===p.personId&&positive(w)).length} Zeitfenster</small></button>`).join('')||'<div class="ux-note">Kein Kollege gefunden.</div>';document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{personId=b.dataset.person;anchor=K.days?.[0]?.date;scope=innerWidth<760?'day':'week';detail()})};$('wsFind').onclick=run;$('wsQuery').oninput=run;run();}
async function copy(sourceId,ids){const p=K.person(sourceId),src=K.wishes.filter(w=>ids.includes(w.id)&&positive(w)),before=JSON.parse(JSON.stringify(K.wishes)),existing=K.wishes.filter(w=>w.personId===K.currentUser.personId&&w.status!=='deleted');if(!confirm(`${src.length} Zeitfenster von ${p.name} übernehmen? Eigene vorhandene Angaben bleiben erhalten.`))return;let added=0,skipped=0;for(const w of src){if(existing.some(x=>x.date===w.date&&x.start===w.start&&x.end===w.end&&x.wishType===w.wishType)){skipped++;continue}K.mutations.saveWish({...w,id:'',personId:K.currentUser.personId,source:'colleague_copy',comment:`Vorlage von ${p.name}`,status:'confirmed'},{reason:'Kollegenplan als Vorlage übernommen'});added++}await K.persistAll?.();K.memberUxData=K.memberUxData||{};K.memberUxData.lastColleagueCopy={sourceId,added,skipped,at:new Date().toISOString()};K.wishSprint.undo=async()=>{K.wishes=before;await K.persistAll?.();search()};alert(`${added} Zeitfenster übernommen${skipped?` · ${skipped} bereits vorhanden`:''}.`);search();}
async function personalizedTemplate(){const user=K.currentUser||{},person=K.person?.(user.personId),name=user.displayName||person?.name||'Mitarbeiter',id=user.personId||person?.personId||'';const XLSX=await (window.XLSX?Promise.resolve(window.XLSX):new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';s.onload=()=>resolve(window.XLSX);s.onerror=()=>reject(new Error('Excel-Komponente konnte nicht geladen werden.'));document.head.appendChild(s)})),r=await fetch('templates/KC_DP2_Wunschzeiten_Vorlage_Weihnachtsmarkt_2026.xlsx'),buf=await r.arrayBuffer(),wb=XLSX.read(buf,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];ws.D4={t:'s',v:name};ws.H4={t:'s',v:id};ws.D5={t:'s',v:user.email||''};const safe=name.replace(/[^A-Za-z0-9ÄÖÜäöüß_-]+/g,'-').replace(/-+/g,'-');XLSX.writeFile(wb,`KC_DP2_Wunschzeiten_${safe}_${id||'ohne-ID'}.xlsx`);}
K.wishSprint={version:'0.19.51a',search,detail,copy,personalizedTemplate,undo:null};
})();