(function(){
'use strict';
const K=window.KCDP=window.KCDP||{},SCHEMA='KC_HANDWRITING_DIGITS_V1',cache=new Map(),key=id=>'handwriting.digits.'+id;
function allowed(id){return !!K.people?.some(p=>p.personId===id&&p.active)&&(K.auth?.has?.('roster.wish.edit_others')||K.currentUser?.personId===id)}
function validate(p){if(p?.schema!==SCHEMA||!K.people?.some(x=>x.personId===p.personId&&x.active)||!Array.isArray(p.samples)||p.samples.length>1000||!p.samples.length)throw Error('Ungültiges Handschriftprofil oder unbekannte Person.');for(const s of p.samples)if(!/^[0-9]$/.test(s.label)||typeof s.bits!=='string'||!/^[01]{768}$/.test(s.bits)||!Number.isFinite(s.ratio)||s.ratio<=0||s.ratio>5)throw Error('Ungültige Ziffernprobe.');return structuredClone(p)}
function pixels(canvas){const {width:w,height:h}=canvas,d=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h).data,a=new Uint8Array(w*h);for(let i=0;i<a.length;i++)a[i]=d[i*4]*.299+d[i*4+1]*.587+d[i*4+2]*.114<160?1:0;return{a,w,h}}
function feature(canvas){const {a,w,h}=pixels(canvas);let x0=w,y0=h,x1=-1,y1=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(a[y*w+x]){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}if(x1<x0)throw Error('Im Ausschnitt ist kein Zeichen.');const bw=x1-x0+1,bh=y1-y0+1;let bits='';for(let y=0;y<32;y++)for(let x=0;x<24;x++){let ink=0,total=0;const left=x0+Math.floor(x*bw/24),right=x0+Math.max(Math.floor((x+1)*bw/24),Math.floor(x*bw/24)+1),top=y0+Math.floor(y*bh/32),bottom=y0+Math.max(Math.floor((y+1)*bh/32),Math.floor(y*bh/32)+1);for(let yy=top;yy<Math.min(bottom,h);yy++)for(let xx=left;xx<Math.min(right,w);xx++){ink+=a[yy*w+xx];total++}bits+=ink/Math.max(1,total)>.17?'1':'0'}return{bits,ratio:bw/bh}}
function distance(a,b){let ink=0,matched=0;for(const [one,two] of [[a.bits,b.bits],[b.bits,a.bits]])for(let i=0;i<768;i++)if(one[i]==='1'){ink++;const x=i%24,y=Math.floor(i/24);let hit=false;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++)if(x+dx>=0&&x+dx<24&&y+dy>=0&&y+dy<32&&two[(y+dy)*24+x+dx]==='1')hit=true;if(hit)matched++}return 1-matched/Math.max(1,ink)+Math.min(.25,Math.abs(Math.log(a.ratio/b.ratio))*.12)}function classify(canvas,profile){const f=feature(canvas),rank=[];for(const label of '0123456789'){const scores=profile.samples.filter(s=>s.label===label).map(s=>distance(f,s));if(scores.length)rank.push({label,score:Math.min(...scores)})}rank.sort((a,b)=>a.score-b.score);const best=rank[0],margin=(rank[1]?.score??1)-(best?.score??1);return{label:best?.label||'',score:best?.score??1,margin,usable:!!best&&best.score<.64&&margin>.025}}
function crop(canvas,r){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(r.w));c.height=Math.max(1,Math.round(r.h));c.getContext('2d').drawImage(canvas,r.x,r.y,r.w,r.h,0,0,c.width,c.height);return c}
function segments(canvas){const {a,w,h}=pixels(canvas),counts=Array.from({length:w},(_,x)=>{let n=0;for(let y=0;y<h;y++)n+=a[y*w+x];return n}),runs=[];let start=null;for(let x=0;x<=w;x++){const ink=x<w&&counts[x]>Math.max(1,h*.008);if(ink&&start===null)start=x;if(!ink&&start!==null){runs.push({x:start,w:x-start});start=null}}const merged=[];for(const r of runs){const last=merged.at(-1);if(last&&r.x-last.x-last.w<=Math.max(1,w*.003))last.w=r.x+r.w-last.x;else merged.push({...r})}return merged.map(r=>{let top=h,bottom=0,count=0;for(let y=0;y<h;y++)for(let x=r.x;x<r.x+r.w;x++)if(a[y*w+x]){top=Math.min(top,y);bottom=Math.max(bottom,y);count++}let gap=0,maxGap=0;for(let yy=top;yy<=bottom;yy++){let rowInk=0;for(let xx=r.x;xx<r.x+r.w;xx++)rowInk+=a[yy*w+xx];gap=rowInk?0:gap+1;maxGap=Math.max(maxGap,gap)}return{...r,y:top,h:bottom-top+1,count,maxGap}}).filter(r=>r.count>3)}
function recognize(canvas,profile){if(!profile)return null;const runs=segments(canvas),maxH=Math.max(0,...runs.map(r=>r.h)),digits=runs.filter(r=>r.h>=maxH*.7&&r.maxGap<r.h*.3);if(![1,2,3,4].includes(digits.length))return null;let text='',worst=0;for(const r of digits){const c=classify(crop(canvas,r),profile);if(!c.usable)return null;text+=c.label;worst=Math.max(worst,c.score)}if(text.length===3)text=text[0]+':'+text.slice(1);if(text.length===4)text=text.slice(0,2)+':'+text.slice(2);return{text,confidence:.54,templateDistance:worst,source:'personal_digits',requiresReview:true}}
async function load(id){if(!id||!allowed(id)||!K.storage?.unlocked)return null;if(cache.has(id))return cache.get(id);const raw=await K.storage.get(key(id));const p=raw?validate(raw):null;if(p)cache.set(id,p);return p}
async function save(p){const clean=validate(p);if(!allowed(clean.personId))throw Error('Keine Berechtigung für dieses Handschriftprofil.');if(!K.storage?.unlocked)throw Error('Bitte zuerst den sicheren Speicher entsperren.');await K.storage.put(key(clean.personId),clean);cache.set(clean.personId,clean);return clean}
async function remove(id){if(!allowed(id))throw Error('Keine Berechtigung.');await K.storage.remove(key(id));cache.delete(id)}
K.handwritingProfiles={version:'0.20.0-b262',schema:SCHEMA,validate,feature,classify,recognize,crop,segments,load,save,remove,allowed,_test:{distance,clear:()=>cache.clear()}};
})();
