(function(){
 const K=window.KCDP=window.KCDP||{};let direct=null;const state={status:'offline',mode:null,lastSyncAt:null,lastError:null,lastSource:null,lastBlock:null};
 const cleanUrl=s=>String(s||'').trim().replace(/\/$/,'');
 function config(){return K.integrationConfig?.pcManager||{};}
 function hostFn(){if(typeof window.KCDPPCManagerProvider==='function')return window.KCDPPCManagerProvider;if(typeof window.KCPCManagerProvider==='function')return window.KCPCManagerProvider;try{if(window.parent&&window.parent!==window&&typeof window.parent.KCPCManagerProvider==='function')return window.parent.KCPCManagerProvider;}catch(_){}return null;}
 function postMessageRequest(payload){return new Promise((resolve,reject)=>{if(!window.parent||window.parent===window)return reject(new Error('Kein eingebetteter PC-Manager-Host gefunden.'));const id='KCDP-PC-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),expected=String(config().expectedOrigin||'').trim(),timer=setTimeout(()=>{cleanup();reject(new Error('PC-Manager antwortet nicht.'));},5000);function cleanup(){clearTimeout(timer);window.removeEventListener('message',onmsg);}function onmsg(e){if(expected&&e.origin!==expected)return;const d=e.data;if(!d||d.type!=='KC_PC_MANAGER_DP_RESPONSE'||d.requestId!==id)return;cleanup();if(d.ok===false)reject(new Error(d.error||'PC-Manager-Fehler'));else resolve(d.payload);}window.addEventListener('message',onmsg);window.parent.postMessage({type:'KC_PC_MANAGER_DP_REQUEST',requestId:id,contract:'KC_PC_MANAGER_DP_BRIDGE_V1',payload},expected||'*');});}
 async function urlRequest(payload){const base=cleanUrl(config().endpoint);if(!base)throw new Error('PC-Manager-Endpunkt fehlt.');if(!/^https:\/\//i.test(base)&&!/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?/i.test(base))throw new Error('PC-Manager-Endpunkt muss HTTPS verwenden (außer localhost).');const r=await fetch(base,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({contract:'KC_PC_MANAGER_DP_BRIDGE_V1',...payload})});if(!r.ok)throw new Error(`PC-Manager HTTP ${r.status}`);return r.json();}
 async function supabaseGet(path){
   const sb=K.supabaseConnection,c=K.integrationConfig?.supabase||{};if(!sb?.ensureSession||!sb?.sessionSnapshot)throw new Error('Supabase-Sitzungsschicht fehlt.');
   await sb.ensureSession();const sess=sb.sessionSnapshot();if(!sess?.access_token)throw new Error('Supabase Auth-Sitzung fehlt.');
   const base=cleanUrl(c.url),key=String(c.publishableKey||'').trim();if(!base||!key)throw new Error('Supabase-Konfiguration fehlt.');
   const r=await fetch(base+path,{method:'GET',mode:'cors',cache:'no-store',headers:{apikey:key,Authorization:'Bearer '+sess.access_token,Accept:'application/json'}});
   let data=null;const text=await r.text();try{data=text?JSON.parse(text):null;}catch(_){data=text;}
   if(!r.ok){const detail=typeof data==='string'?data:(data?.message||data?.hint||data?.error||'Request fehlgeschlagen');throw new Error(`Manager/Core-Lesezugriff HTTP ${r.status}: ${detail}`);}return data;
 }
 function sectionPayload(rows,key){const row=(Array.isArray(rows)?rows:[]).find(x=>x.section_key===key);return row?.payload&&typeof row.payload==='object'?row.payload:{};}
 async function supabaseSnapshot(){
   const c=K.integrationConfig?.supabase||{},org=encodeURIComponent(c.orgId||'');if(!org)throw new Error('Organisation fehlt.');
   const directory=await supabaseGet(`/rest/v1/kc_core_operational_directory?select=person_id,display_name,preferred_name,active&org_id=eq.${org}&active=is.true&order=person_id.asc`);
   const sections=await supabaseGet(`/rest/v1/kc_manager_state_sections?select=section_key,payload,version,updated_at&org_id=eq.${org}&section_key=in.(dienstplan_people,dienstplan_context,dienstplan_publication)`);
   const peopleCfg=sectionPayload(sections,'dienstplan_people'),context=sectionPayload(sections,'dienstplan_context'),publicationRaw=sectionPayload(sections,'dienstplan_publication');
   const details=Array.isArray(peopleCfg.items)?peopleCfg.items:(Array.isArray(peopleCfg.people)?peopleCfg.people:[]),detailById=new Map(details.map(x=>[String(x?.personId||x?.person_id||''),x]));
   const people=(Array.isArray(directory)?directory:[]).map(row=>{const d=detailById.get(String(row.person_id))||{};return {...d,personId:String(row.person_id),displayName:row.preferred_name||row.display_name,active:row.active!==false};});
   const publication=publicationRaw.publication&&typeof publicationRaw.publication==='object'?publicationRaw.publication:publicationRaw;
   return {contract:'KC_PC_MANAGER_DP_BRIDGE_V1',people,weather:context.weather||null,program:context.program||null,event:context.event||null,publication,meta:{source:'supabase_core_manager',peopleRows:people.length,managerSections:Array.isArray(sections)?sections.length:0}};
 }
 async function supabaseRequest(payload){const s=await supabaseSnapshot();if(payload?.action==='health')return {ok:true,meta:s.meta,publication:s.publication};if(payload?.action==='people')return s;if(payload?.action==='weather')return {weather:s.weather,publication:s.publication,meta:s.meta};if(payload?.action==='program')return {program:s.program,publication:s.publication,meta:s.meta};return s;}
 async function request(payload){const c=config(),fn=direct||hostFn();state.mode=c.mode||'host';state.status='connecting';try{let out;if(direct)out=await direct({...payload,contract:'KC_PC_MANAGER_DP_BRIDGE_V1'});else if(c.mode==='url')out=await urlRequest(payload);else if(fn)out=await fn({...payload,contract:'KC_PC_MANAGER_DP_BRIDGE_V1'});else if(c.mode==='supabase'||K.supabaseConnection){state.mode='supabase';out=await supabaseRequest(payload);}else out=await postMessageRequest(payload);state.status='ready';state.lastError=null;state.lastSource=out?.meta?.source||state.mode||'host';return out;}catch(e){state.status='error';state.lastError=e.message;throw e;}}
 function normalizeWeather(snapshot,date){const w=snapshot?.weather;if(!w)return null;if(Array.isArray(w))return w.find(x=>x.date===date)||null;if(w[date])return w[date];if(w.date===date||!w.date)return w;return null;}
 function normalizeProgram(snapshot,date){const p=snapshot?.program;if(!p)return[];if(Array.isArray(p))return p.filter(x=>!x.date||x.date===date);if(Array.isArray(p[date]))return p[date];if(Array.isArray(p.items))return p.items.filter(x=>!x.date||x.date===date);return[];}
 async function snapshot(){return request({action:'snapshot',eventId:K.eventConfig?.eventId,dateFrom:K.days?.[0]?.date,dateTo:K.days?.at?.(-1)?.date});}
 function contextPublicationOk(s){const p=s?.publication?.context||s?.meta?.contextPublication||s?.contextPublication||{};return (p.published===true||p.status==='published')&&p.complete===true;}
 function applyContext(s){for(const d of K.days||[]){const w=normalizeWeather(s,d.date);if(w)d.weather={...d.weather,...w,source:w.source||s?.meta?.source||'PC Manager',fetchedAt:w.fetchedAt||new Date().toISOString()};const p=normalizeProgram(s,d.date);if(p.length)d.program=p;}if(s?.event&&K.configuration){K.configuration.updateEvent({name:s.event.name||K.eventConfig.name});for(const x of s.event.days||[]){if(K.days.some(d=>d.date===x.date))K.configuration.updateDay(x.date,x);}}}
 async function syncAll(){
   K.auth?.require?.('roster.people.sync','Sie dürfen PC-Manager-Daten nicht übernehmen.');
   const s=await snapshot();if(s?.contract&&s.contract!=='KC_PC_MANAGER_DP_BRIDGE_V1')throw new Error('PC-Manager-Vertrag nicht kompatibel.');
   const peopleResult=K.personAdapter?.applyAuthoritativeSnapshot?.(s?.people,{source:s?.meta?.source||'pc_manager_bridge',snapshot:s});
   if(!peopleResult?.applied){state.status='blocked';state.lastBlock={at:new Date().toISOString(),code:peopleResult?.code||'PEOPLE_NOT_READY',reason:peopleResult?.reason||'PC-Manager-Personendaten sind nicht freigegeben.'};K.recordAudit?.('pc_manager.sync_blocked',{entity:'pc_manager',after:{...state.lastBlock,source:state.lastSource}});return {...s,kcDpApply:{applied:false,people:peopleResult,contextApplied:false}};}
   const contextReady=contextPublicationOk(s);if(contextReady)applyContext(s);
   state.status=contextReady?'ready':'partial';state.lastBlock=contextReady?null:{at:new Date().toISOString(),code:'CONTEXT_NOT_PUBLISHED_COMPLETE',reason:'Wetter/Programm sind noch nicht vollständig freigegeben.'};state.lastSyncAt=new Date().toISOString();
   K.recordAudit?.('pc_manager.sync_all',{entity:'pc_manager',after:{people:peopleResult.people.length,weather:contextReady&&!!s?.weather,program:contextReady&&!!s?.program,contextApplied:contextReady,source:state.lastSource}});
   return {...s,kcDpApply:{applied:true,people:peopleResult,contextApplied:contextReady}};
 }
 async function test(){const r=await request({action:'health'});return {ok:r?.ok!==false,status:state.status,source:state.lastSource,response:r};}
 function bindProviders(){const c=config(),available=!!(direct||hostFn()||(c.mode==='url'&&cleanUrl(c.endpoint))||K.supabaseConnection||(window.parent&&window.parent!==window));if(!available){K.personAdapter?.setProvider?.(null);K.contextProviders?.setWeatherProvider?.(null);K.contextProviders?.setProgramProvider?.(null);state.status='offline';return false;}K.personAdapter?.setProvider?.(async req=>request(req.action==='listPeople'?{action:'people'}:req));K.contextProviders?.setWeatherProvider?.({fetch:async({date})=>{const r=await request({action:'weather',date,eventId:K.eventConfig?.eventId});return r?.weather?.[date]||r?.weather||r;}});K.contextProviders?.setProgramProvider?.({fetch:async({date})=>{const r=await request({action:'program',date,eventId:K.eventConfig?.eventId});return r?.program?.[date]||r?.items||r?.program||r;}});state.status='configured';return true;}
 function configure(patch={}){K.integrations?.update?.('pcManager',patch);bindProviders();state.status='configured';return {...config()};}
 K.pcManagerConnection={version:'0.19.42',contract:'KC_PC_MANAGER_DP_BRIDGE_V1',state,configure,setDirectProvider(fn){direct=typeof fn==='function'?fn:null;bindProviders();state.status=direct?'ready':'configured';},bindProviders,test,snapshot,syncAll,contextPublicationOk,supabaseSnapshot};
 bindProviders();
})();
