(function(){
 const K=window.KCDP=window.KCDP||{};
 const LOGO_SVG_B64='PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxNjAgMTIwIiByb2xlPSJpbWciIGFyaWEtbGFiZWw9IkvDtmNoZWNsdWIgV2VybmUgTG9nbyI+CiAgPHJlY3Qgd2lkdGg9IjE2MCIgaGVpZ2h0PSIxMjAiIGZpbGw9IndoaXRlIi8+CiAgPGcgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMTExIiBzdHJva2Utd2lkdGg9IjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCI+CiAgICA8cGF0aCBkPSJNNDkgNTljLTEzLTItMjItMTItMjItMjQgMC0xMyAxMC0yMyAyMy0yNCA1LTggMTQtMTIgMjQtMTAgOCAxIDE0IDYgMTggMTIgNS00IDEyLTYgMTgtNCAxMSAyIDE5IDEyIDE5IDIzIDAgMTItOCAyMi0yMCAyNSIvPgogICAgPHBhdGggZD0iTTQ4IDU2aDYzbC01IDM3SDUzeiIvPgogICAgPHBhdGggZD0iTTYxIDY4aDM3Ii8+CiAgPC9nPgogIDx0ZXh0IHg9IjgwIiB5PSIxMTEiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZvbnQtZmFtaWx5PSJBcmlhbCwgc2Fucy1zZXJpZiIgZm9udC1zaXplPSIxMyIgZm9udC13ZWlnaHQ9IjcwMCI+S8OWQ0hFQ0xVQiBXRVJORTwvdGV4dD4KPC9zdmc+Cg==';
 const PAGE_W=842,PAGE_H=595,MARGIN=34;
 const clean=s=>String(s??'').replace(/[\u2013\u2014]/g,'-').replace(/[\u2018\u2019]/g,"'").replace(/[\u201c\u201d]/g,'"').replace(/\s+/g,' ').trim();
 const pdfEsc=s=>clean(s).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\xFF]/g,'?');
 const bytesLatin=s=>Uint8Array.from([...String(s)].map(ch=>{const c=ch.charCodeAt(0);return c<=255?c:63;}));
 const concat=parts=>{const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;};
 const b64bytes=b64=>Uint8Array.from(atob(b64),c=>c.charCodeAt(0));
 const base64=u8=>{let s='',chunk=0x8000;for(let i=0;i<u8.length;i+=chunk)s+=String.fromCharCode(...u8.subarray(i,i+chunk));return btoa(s);};
 const txt=(x,y,size,text,font='F1')=>`BT /${font} ${size} Tf ${x.toFixed(1)} ${y.toFixed(1)} Td (${pdfEsc(text)}) Tj ET`;
 const line=(x1,y1,x2,y2,w=.6)=>`${w} w ${x1.toFixed(1)} ${y1.toFixed(1)} m ${x2.toFixed(1)} ${y2.toFixed(1)} l S`;
 const rect=(x,y,w,h,{fill=null,stroke=.65}={})=>`${fill?`${fill} rg ${x.toFixed(1)} ${y.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)} re f `:''}${stroke?`${stroke} w 0 G ${x.toFixed(1)} ${y.toFixed(1)} ${w.toFixed(1)} ${h.toFixed(1)} re S`:''}`;
 function wrap(text,maxChars){const words=clean(text).split(' ').filter(Boolean),out=[];let cur='';for(const w of words){if(!cur){cur=w;continue;}if((cur+' '+w).length<=maxChars)cur+=' '+w;else{out.push(cur);cur=w;}}if(cur)out.push(cur);return out.length?out:[''];}
 function parse(html){const root=document.createElement('div');root.innerHTML=html;return [...root.querySelectorAll('.doc-page')];}
 function tableData(table){return [...table.querySelectorAll('tr')].map(tr=>[...tr.children].map(c=>({text:clean(c.textContent),header:c.tagName==='TH',cls:c.className||''})));}
 function colWidths(rows,total){const cols=Math.max(1,...rows.map(r=>r.length)),weights=Array(cols).fill(5);for(const r of rows)r.forEach((c,i)=>weights[i]=Math.min(34,Math.max(weights[i],Math.min(34,c.text.length+3))));const sum=weights.reduce((a,b)=>a+b,0);return weights.map(w=>total*w/sum);}
 async function logoJpeg(){return new Promise(resolve=>{try{const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=420;c.height=300;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);g.drawImage(img,0,0,c.width,c.height);const url=c.toDataURL('image/jpeg',.94);resolve({bytes:b64bytes(url.split(',')[1]),width:c.width,height:c.height});}catch(_){resolve(null)}};img.onerror=()=>resolve(null);img.src='data:image/svg+xml;base64,'+LOGO_SVG_B64;}catch(_){resolve(null)}})}
 function drawTable(table,y,cmds){const rows=tableData(table),widths=colWidths(rows,PAGE_W-2*MARGIN),x0=MARGIN,font=7.4,lineH=9.2;for(let ri=0;ri<rows.length;ri++){const r=rows[ri],wrapped=r.map((c,i)=>wrap(c.text,Math.max(5,Math.floor(widths[i]/4.5)))),lines=Math.max(1,...wrapped.map(x=>x.length)),rh=Math.max(21,lines*lineH+8);if(y-rh<48)break;let x=x0;for(let ci=0;ci<r.length;ci++){const c=r[ci],w=widths[ci],bg=c.header?'.91 .91 .91':c.cls.includes('status-bad')?'.98 .90 .90':c.cls.includes('status-over')?'1 .96 .83':c.cls.includes('status-ok')?'.91 .97 .91':null;cmds.push(rect(x,y-rh,w,rh,{fill:bg,stroke:.55}),'0 g');const lines=wrapped[ci];lines.slice(0,4).forEach((t,li)=>cmds.push(txt(x+4,y-11-li*lineH,font,t,c.header?'F2':'F1')));x+=w;}y-=rh;}return y-8;}
 function drawNote(el,y,cmds){const lines=wrap(el.textContent,122),h=Math.max(28,lines.length*10+12);cmds.push(rect(MARGIN,y-h,PAGE_W-2*MARGIN,h,{fill:'.96 .96 .96',stroke:.55}),'0 g');lines.slice(0,6).forEach((t,i)=>cmds.push(txt(MARGIN+7,y-12-i*10,8,t)));return y-h-8;}
 function drawSignature(el,y,cmds){const parts=[...el.children].map(x=>clean(x.textContent));const w=(PAGE_W-2*MARGIN-24)/Math.max(1,parts.length);parts.forEach((p,i)=>{const x=MARGIN+i*(w+12);cmds.push(line(x,y-16,x+w,y-16,.55),txt(x,y-28,7.5,p));});return y-40;}
 function pageCommands(page,logo,pageNo,total){const cmds=[];if(logo)cmds.push(`q 74 0 0 52 ${MARGIN} 500 cm /Logo Do Q`);else{cmds.push(rect(MARGIN,500,74,52,{fill:'.96 .96 .96',stroke:.5}),txt(MARGIN+8,525,9,'KC WERNE','F2'));}
 const club=clean(page.querySelector('.doc-club b')?.textContent||'Köcheclub Werne'),title=clean(page.querySelector('.doc-club .title')?.textContent||'KC DP'),period=clean(page.querySelector('.doc-club .doc-period')?.textContent||''),meta=[...page.querySelectorAll('.doc-meta > div')].map(x=>clean(x.textContent));cmds.push(txt(305,541,15,club,'F2'),txt(330,521,12,title,'F2'));if(period)cmds.push(txt(302,505,8.5,period,'F2'));meta.slice(0,3).forEach((m,i)=>wrap(m,42).slice(0,2).forEach((t,j)=>cmds.push(txt(625,544-i*17-j*9,7.5,t))));cmds.push(line(MARGIN,492,PAGE_W-MARGIN,492,1.1));
 const wm=clean(page.querySelector('.doc-watermark')?.textContent||'');if(wm)cmds.push('0.88 g',txt(330,290,32,wm,'F2'),'0 g');let y=472;
 for(const el of [...page.children]){if(el.matches('.doc-header,.doc-footer,.doc-watermark'))continue;if(el.matches('.doc-sub')){wrap(el.textContent,125).slice(0,3).forEach((t,i)=>cmds.push(txt(MARGIN,y-i*11,8.4,t,i===0?'F2':'F1')));y-=26;}else if(el.tagName==='TABLE')y=drawTable(el,y,cmds);else if(el.matches('.note'))y=drawNote(el,y,cmds);else if(el.matches('.signature'))y=drawSignature(el,y,cmds);else{const t=clean(el.textContent);if(t){wrap(t,125).slice(0,8).forEach((z,i)=>cmds.push(txt(MARGIN,y-i*10,8,z)));y-=Math.min(80,wrap(t,125).length*10+7);}}if(y<55)break;}
 cmds.push(line(MARGIN,31,PAGE_W-MARGIN,31,.55),'0 g');const footer=page.querySelector('.doc-footer'),f1=clean(footer?.children?.[0]?.textContent||'Köcheclub Werne · Internes Clubdokument'),f2=clean(footer?.children?.[1]?.textContent||`Seite ${pageNo} von ${total}`),f3=clean(footer?.children?.[2]?.textContent||'KC DP');cmds.push(txt(MARGIN,18,7.4,f1),txt(382,18,7.4,f2),txt(700,18,7.1,f3));return cmds.join('\n');}
 async function buildPages(pages){if(!pages.length)throw new Error('Dokument enthält keine druckbaren Seiten.');const logo=await logoJpeg();const objs=[];const add=(body,binary=null)=>{objs.push({body,binary});return objs.length;};const f1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),f2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>');let logoId=null;if(logo)logoId=add(`<< /Type /XObject /Subtype /Image /Width ${logo.width} /Height ${logo.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${logo.bytes.length} >>`,logo.bytes);const pageIds=[],contentIds=[];for(let i=0;i<pages.length;i++){const stream=bytesLatin(pageCommands(pages[i],logo,i+1,pages.length));contentIds.push(add(`<< /Length ${stream.length} >>`,stream));pageIds.push(add('PAGE_PLACEHOLDER'));}const pagesId=add('PAGES_PLACEHOLDER'),catalog=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);for(let i=0;i<pageIds.length;i++){const xobj=logoId?` /XObject << /Logo ${logoId} 0 R >>`:'';objs[pageIds[i]-1].body=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${PAGE_W} ${PAGE_H}] /Resources << /Font << /F1 ${f1} 0 R /F2 ${f2} 0 R >>${xobj} >> /Contents ${contentIds[i]} 0 R >>`;}objs[pagesId-1].body=`<< /Type /Pages /Kids [${pageIds.map(id=>id+' 0 R').join(' ')}] /Count ${pageIds.length} >>`;
 const chunks=[bytesLatin('%PDF-1.4\n%KC-DP\n')],offsets=[0];let offset=chunks[0].length;for(let i=0;i<objs.length;i++){offsets.push(offset);const pre=bytesLatin(`${i+1} 0 obj\n${objs[i].body}${objs[i].binary?'\nstream\n':'\n'}`),post=bytesLatin(objs[i].binary?'\nendstream\nendobj\n':'endobj\n');chunks.push(pre);offset+=pre.length;if(objs[i].binary){chunks.push(objs[i].binary);offset+=objs[i].binary.length;}chunks.push(post);offset+=post.length;}const xref=offset;let tail=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`;for(let i=1;i<offsets.length;i++)tail+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';tail+=`trailer\n<< /Size ${objs.length+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`;chunks.push(bytesLatin(tail));return concat(chunks);}
 async function build(doc){return buildPages(parse(doc.html));}
 async function download(doc){const b=await build(doc),blob=new Blob([b],{type:'application/pdf'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(doc.fileName||'KC_DP.pdf').replace(/\.html$/i,'.pdf');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200);return {bytes:b,fileName:a.download};}
 async function attachment(doc){const b=await build(doc);return {fileName:(doc.fileName||'KC_DP.pdf').replace(/\.html$/i,'.pdf'),mimeType:'application/pdf',bytesBase64:base64(b),size:b.length};}
 K.pdfAdapter={version:'0.16.0',bytes:build,base64,download,attachment,_test:{pageCommands,buildPages}};
})();
