(function(){
'use strict';
if(window.XLSX)return;
const td=new TextDecoder('utf-8');
const u16=(d,o)=>d[o]|d[o+1]<<8, u32=(d,o)=>(d[o]|d[o+1]<<8|d[o+2]<<16|d[o+3]<<24)>>>0;
const rev=(v,n)=>{let r=0;while(n--)r=r<<1|v&1,v>>>=1;return r};
function huff(lengths){let max=0;for(const n of lengths)if(n>max)max=n;const count=new Array(max+1).fill(0),next=new Array(max+1).fill(0),map=new Map;for(const n of lengths)if(n)count[n]++;let code=0;for(let n=1;n<=max;n++){code=(code+count[n-1])<<1;next[n]=code;}lengths.forEach((n,s)=>{if(n)map.set(n+':'+rev(next[n]++,n),s)});return {max,map};}
function inflate(src){let p=0,bits=0,nb=0,out=[];const need=n=>{while(nb<n){bits|=src[p++]<<nb;nb+=8;}},get=n=>{need(n);const v=bits&((1<<n)-1);bits>>>=n;nb-=n;return v},sym=h=>{let c=0;for(let n=1;n<=h.max;n++){c|=get(1)<<(n-1);const v=h.map.get(n+':'+c);if(v!==undefined)return v;}throw Error('Ungültiger DEFLATE-Code');};
 const fixed=()=>{const l=new Array(288);for(let i=0;i<=143;i++)l[i]=8;for(let i=144;i<=255;i++)l[i]=9;for(let i=256;i<=279;i++)l[i]=7;for(let i=280;i<=287;i++)l[i]=8;return [huff(l),huff(new Array(32).fill(5))]};
 const LB=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],LE=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],DB=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],DE=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];
 let last=0;while(!last){last=get(1);const type=get(2);if(type===0){bits=0;nb=0;const len=src[p]|src[p+1]<<8;p+=4;for(let i=0;i<len;i++)out.push(src[p++]);continue;}let lh,dh;if(type===1)[lh,dh]=fixed();else if(type===2){const hl=get(5)+257,hd=get(5)+1,hc=get(4)+4,ord=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],cl=new Array(19).fill(0);for(let i=0;i<hc;i++)cl[ord[i]]=get(3);const ch=huff(cl),lens=[];while(lens.length<hl+hd){const s=sym(ch);if(s<16)lens.push(s);else if(s===16){const prev=lens[lens.length-1],n=get(2)+3;for(let i=0;i<n;i++)lens.push(prev);}else if(s===17){const n=get(3)+3;for(let i=0;i<n;i++)lens.push(0);}else{const n=get(7)+11;for(let i=0;i<n;i++)lens.push(0);}}lh=huff(lens.slice(0,hl));dh=huff(lens.slice(hl,hl+hd));}else throw Error('Ungültiger DEFLATE-Block');
  for(;;){const s=sym(lh);if(s<256){out.push(s);continue;}if(s===256)break;const li=s-257;if(li<0||li>=LB.length)throw Error('Ungültige Längencodierung');const len=LB[li]+(LE[li]?get(LE[li]):0),ds=sym(dh);if(ds>=DB.length)throw Error('Ungültige Distanzcodierung');const dist=DB[ds]+(DE[ds]?get(DE[ds]):0);for(let i=0;i<len;i++)out.push(out[out.length-dist]);}
 }
 return new Uint8Array(out);
}
function unzip(buf){const d=new Uint8Array(buf);let e=d.length-22;for(;e>=0&&u32(d,e)!==0x06054b50;e--);if(e<0)throw Error('Keine gültige XLSX-Datei.');const count=u16(d,e+10),cd=u32(d,e+16),files={};let p=cd;for(let i=0;i<count;i++){if(u32(d,p)!==0x02014b50)throw Error('XLSX-ZIP-Verzeichnis beschädigt.');const method=u16(d,p+10),cs=u32(d,p+20),ns=u16(d,p+28),es=u16(d,p+30),csz=u16(d,p+32),off=u32(d,p+42),name=td.decode(d.slice(p+46,p+46+ns));const ln=u16(d,off+26),le=u16(d,off+28),start=off+30+ln+le,raw=d.slice(start,start+cs);files[name]=method===0?raw:method===8?inflate(raw):null;p+=46+ns+es+csz;}return files;}
const entity=s=>String(s||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(+n)).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)));
const texts=xml=>[...String(xml||'').matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(m=>entity(m[1])).join('');
const textsList=xml=>[...String(xml).matchAll(/<si>([\s\S]*?)<\/si>/g)].map(m=>texts(m[1]));
const col=r=>{let n=0;for(const ch of r.replace(/\d/g,''))n=n*26+ch.charCodeAt(0)-64;return n-1};
function matrix(xml,shared){const rows=[];for(const m of String(xml).matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>|<c\b([^>]*)\/>/g)){const a=m[1]||m[3]||'',body=m[2]||'',rm=a.match(/\br="([A-Z]+\d+)"/),tm=a.match(/\bt="([^"]+)"/);if(!rm)continue;const ref=rm[1],ri=parseInt(ref.match(/\d+/)[0],10)-1,ci=col(ref),t=tm?tm[1]:'',vm=body.match(/<v>([\s\S]*?)<\/v>/);let v='';if(t==='inlineStr')v=texts(body);else if(vm){const raw=entity(vm[1]);if(t==='s')v=shared[+raw]??'';else if(t==='b')v=raw==='1';else if(t==='str'||t==='e')v=raw;else v=raw===''?'':Number.isFinite(Number(raw))?Number(raw):raw;}rows[ri]=rows[ri]||[];rows[ri][ci]=v;}for(let i=0;i<rows.length;i++)rows[i]=rows[i]||[];return rows;}
function read(buf){const f=unzip(buf),ss=f['xl/sharedStrings.xml']?textsList(td.decode(f['xl/sharedStrings.xml'])):[],sheet=Object.keys(f).filter(x=>/^xl\/worksheets\/sheet\d+\.xml$/.test(x)).sort((a,b)=>parseInt(a.match(/\d+/)[0])-parseInt(b.match(/\d+/)[0]))[0];if(!sheet)throw Error('Keine Tabelle in der XLSX-Datei gefunden.');return {SheetNames:['Tabelle1'],Sheets:{Tabelle1:{__matrix:matrix(td.decode(f[sheet]),ss)}}};}
window.XLSX={version:'KC-local-1.0',read,utils:{sheet_to_json(ws,opt){const rows=ws&&ws.__matrix?ws.__matrix:[];if(opt&&opt.header===1)return rows;return rows;}}};
})();
