(function(){
  const K=window.KCDP=window.KCDP||{};
  K.deliveryLog=K.deliveryLog||[];
  const emailOf=p=>p?.email||p?.contacts?.email||null;
  function recipients(ids){return (ids||[]).map(id=>K.person(id)).filter(Boolean);}
  function canDistribute(doc){if(doc.scope==='personal')return K.auth?.has('roster.documents.personal')||K.auth?.has('roster.export.personal')||K.auth?.has('*');return K.auth?.has('roster.documents.distribute')||K.auth?.has('*');}
  function prepare(doc,personIds,{subject=null,message=null}={}){if(!canDistribute(doc))throw new Error('Keine Berechtigung für diesen Dokumentversand.');const ids=[...new Set(personIds||[])];if(doc.scope==='personal'){if(!doc.personId)throw new Error('Persönliches Dokument hat keine eindeutige Person-ID.');if(ids.some(id=>id!==doc.personId))throw new Error('Ein persönlicher Dienstplan darf nur an die zugehörige Person versendet werden.');if(doc.personId!==K.currentUser?.personId&&!K.auth?.has?.('roster.documents.distribute')&&!K.auth?.has?.('*'))throw new Error('Sie dürfen nur Ihren eigenen persönlichen Dienstplan versenden.');}const people=recipients(ids),jobs=people.map(p=>({id:`MAIL-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,documentId:doc.id,personId:p.personId,name:p.name,email:emailOf(p),subject:subject||`Köcheclub Werne – ${doc.title}`,message:message||`Im Anhang / Dokumentpaket finden Sie: ${doc.title}.`,status:emailOf(p)?'prepared':'missing_email',createdAt:new Date().toISOString()}));return jobs;}
  async function sendPrepared(doc,jobs){const results=[];for(const job of jobs){if(job.status==='missing_email'){results.push(job);continue;}if(!K.emailAdapter?.hasProvider?.()){job.status='provider_missing';results.push(job);continue;}try{const attachment=K.pdfAdapter?.attachment?await K.pdfAdapter.attachment(doc):null;const result=await K.emailAdapter.send({to:job.email,subject:job.subject,text:job.message,document:{fileName:doc.fileName,html:doc.html,fingerprint:doc.fingerprint},attachments:attachment?[attachment]:[]});job.status='sent';job.sentAt=new Date().toISOString();job.providerResult=result||null;}catch(e){job.status='failed';job.error=e.message;}results.push(job);}const log={id:`DEL-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,at:new Date().toISOString(),documentId:doc.id,type:doc.type,fingerprint:doc.fingerprint,results:JSON.parse(JSON.stringify(results)),actorPersonId:K.currentUser?.personId||null};K.deliveryLog.push(log);K.documents?.register?.(doc,{action:'distribution',recipients:results.map(r=>({personId:r.personId,status:r.status}))});return results;}
  function stats(results){const s={total:results.length,sent:0,failed:0,missing:0,prepared:0};for(const r of results){if(r.status==='sent')s.sent++;else if(r.status==='missing_email')s.missing++;else if(r.status==='failed'||r.status==='provider_missing')s.failed++;else s.prepared++;}return s;}
  async function sendPersonalPlans(start,end,personIds){const results=[];for(const personId of personIds||[]){const doc=K.documents.build({type:'personal',personId,start,end,publishedOnly:true});const jobs=prepare(doc,[personId]);results.push(...await sendPrepared(doc,jobs));}return results;}
  K.distribution={version:'0.16.0',prepare,sendPrepared,sendPersonalPlans,stats,canDistribute};
})();
