(function(){
  const K=window.KCDP=window.KCDP||{},clamp=v=>Math.max(0,Math.min(100,Math.round(v)));
  const weights={coverage:35,zone:15,roles:15,qualifications:10,wishes:10,breaks:5,fairness:5,context:5};
  function quality(start=K.days[0].date,end=K.days.at(-1).date){const ds=K.days.filter(d=>d.date>=start&&d.date<=end);let slots=0,covered=0,zoneSlots=0,zoneOk=0,roleChecks=0,roleOk=0,wishBad=0,breakIssues=0,contextOk=0;for(const d of ds){for(let t=d.start;t<d.end;t+=.25){slots++;const c=K.coverageAt(d,t);if(c.total>=c.req.total)covered++;if(d.type==='market'){zoneSlots+=2;if(c.front>=c.req.front)zoneOk++;if(c.back>=c.req.back)zoneOk++;}for(const role of c.req.requiredRoles||[]){roleChecks++;if(c.active.some(s=>(K.person(s.personId)?.skills||'').toLowerCase().includes(String(role).toLowerCase())))roleOk++;}if((d.weather?.fetchedAt||d.weather?.updatedAt))contextOk++;}const shifts=(K.visiblePlannedShifts?K.visiblePlannedShifts(d.date):K.shifts.filter(s=>s.date===d.date&&s.layer==='planned'));wishBad+=shifts.filter(s=>K.wishCoverage(s.personId,s.date,s.start,s.end).unavailable).length;breakIssues+=shifts.flatMap(s=>K.breaks?.compliance?.(s)?.issues||[]).length;}
    const fairness=K.analytics?.fairness?.(start,end)?.overall??100;const components={coverage:slots?covered/slots*100:100,zone:zoneSlots?zoneOk/zoneSlots*100:100,roles:roleChecks?roleOk/roleChecks*100:100,qualifications:100,wishes:clamp(100-wishBad*8),breaks:clamp(100-breakIssues*5),fairness,context:slots?Math.min(100,contextOk/slots*100+50):100};let score=0;for(const [k,w] of Object.entries(weights))score+=(components[k]??100)*w/100;const hardCritical=ds.some(d=>K.evaluateDay(d).under>0);return {score:clamp(score),hardCritical,status:hardCritical?'red':score>=90?'green':score>=75?'yellow':'red',components,weights:{...weights}};}
  function setWeather(date,{temp,condition,impact,factor,fetchedAt=new Date().toISOString(),source='manual'}={}){K.auth?.require?.('roster.weather.override','Keine Berechtigung für Wetter-Override.');const d=K.days.find(x=>x.date===date);if(!d)throw new Error('Tag nicht gefunden.');d.weather={...d.weather,temp:Number(temp),condition:String(condition||''),impact:String(impact||'neutral'),factor:Number(factor||1),fetchedAt,source};K.recordAudit?.('weather.override',{entity:'weather',entityId:date,after:d.weather});return d.weather;}
  function setProgram(date,items){K.auth?.require?.('roster.program.edit_impact','Keine Berechtigung für Programmwirkung.');const d=K.days.find(x=>x.date===date);if(!d)throw new Error('Tag nicht gefunden.');d.program=(items||[]).map((p,i)=>({id:p.id||`PRG-${date}-${i}`,title:String(p.title||'Programmpunkt'),start:Number(p.start),end:Number(p.end),impact:p.impact||'0',frontDelta:Number(p.frontDelta||0),backDelta:Number(p.backDelta||0),leadMinutes:Number(p.leadMinutes??30),lagMinutes:Number(p.lagMinutes??30)}));K.recordAudit?.('program.update',{entity:'program',entityId:date,after:d.program});return d.program;}
  function simulateAbsence(shiftId){const s=K.shifts.find(x=>x.id===shiftId);if(!s)throw new Error('Dienst nicht gefunden.');const d=K.days.find(x=>x.date===s.date),before=K.evaluateDay(d),after=K.evaluateDay(d,{...s,status:'absent'}),search=K.staffing?.replacementSearch?.({date:s.date,start:s.start,end:s.end,zone:s.zone,area:s.area,excludePersonId:s.personId,replacementForShiftId:s.id})||{candidates:[]};return {shift:s,day:d,before,after,candidates:search.candidates||[],deltaCritical:after.critical-before.critical,deltaQuality:after.quality-before.quality};}
  K.intelligence={version:'0.13.0',quality,setWeather,setProgram,simulateAbsence,weights};
})();
