(function(){
'use strict';
const K=window.KCDP=window.KCDP||{};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const safe=v=>String(v||'Person').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9_-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')||'Person';
const fmtDate=iso=>String(iso||'').replace(/^(\d{4})-(\d{2})-(\d{2})$/,'$3.$2.$1');
const fmtTime=h=>`${String(Math.floor(Number(h)||0)).padStart(2,'0')}:${String(Math.round(((Number(h)||0)%1)*60)).padStart(2,'0')}`;
const range=()=>({start:K.days?.[0]?.date||'',end:K.days?.[K.days.length-1]?.date||''});
function profileFor(person){
  if(!person)throw new Error('Bitte zuerst eine Person auswählen.');
  if(!person.formProfileId){person.formProfileId=`HP-${K.documentIdentity?.randomCode?.(12)||Math.random().toString(36).slice(2,14).toUpperCase()}`;K.persistAll?.().catch?.(()=>{});}
  const r=range(),periodId=`${r.start}_${r.end}`;
  return{profileId:person.formProfileId,periodId,payload:JSON.stringify({schema:'KCDP-FORM-PROFILE-1',profileId:person.formProfileId,periodId})};
}
function loadQr(){if(typeof window.qrcode==='function')return Promise.resolve(window.qrcode);return new Promise((resolve,reject)=>{const old=document.getElementById('kcQrGenerator');if(old){old.addEventListener('load',()=>resolve(window.qrcode),{once:true});old.addEventListener('error',()=>reject(new Error('QR-Komponente konnte nicht geladen werden.')), {once:true});return}const s=document.createElement('script');s.id='kcQrGenerator';s.src='https://cdn.jsdelivr.net/npm/qrcode-generator@2.0.4/dist/qrcode.js';s.crossOrigin='anonymous';s.onload=()=>typeof window.qrcode==='function'?resolve(window.qrcode):reject(new Error('QR-Komponente ist unvollständig.'));s.onerror=()=>reject(new Error('QR-Komponente konnte nicht geladen werden. Internetverbindung prüfen.'));document.head.appendChild(s)})}
async function qrFor(payload){const create=await loadQr(),qr=create(0,'M');qr.addData(payload);qr.make();const quiet=4,n=qr.getModuleCount(),out=Array.from({length:n+quiet*2},()=>Array(n+quiet*2).fill(false));for(let r=0;r<n;r++)for(let c=0;c<n;c++)out[r+quiet][c+quiet]=qr.isDark(r,c);return out}
const header=(title,person,profile)=>`<header class="doc-header"><div></div><div class="doc-club"><b>Köcheclub Werne</b><div class="title">${esc(title)}</div><div class="doc-period">${fmtDate(range().start)} bis ${fmtDate(range().end)}</div></div><div class="doc-meta"><div><b>Person</b> ${esc(person.name)}</div><div><b>Profil</b> ${esc(profile.profileId)}</div></div></header>`;
const footer=(profile,page,total)=>`<footer class="doc-footer"><span>KC DP2 · personalisierte Arbeitsunterlage</span><span>Seite ${page} von ${total}</span><span>${esc(profile.profileId)}</span></footer>`;
const page=(title,person,profile,body,index,total)=>`<section class="doc-page">${header(title,person,profile)}${body}${footer(profile,index,total)}</section>`;
function matrixDoc(person,profile,qrMatrix){
  const dayName=d=>new Intl.DateTimeFormat('de-DE',{weekday:'short'}).format(new Date(d.date+'T12:00:00')).replace('.',''),area=d=>d.type==='prep'?'Vorbereitung':d.type==='after'?'Nachbereitung':'Weihnachtsmarkt';
  const rows=(K.days||[]).map(d=>`<tr><td>${fmtDate(d.date)}</td><td>${dayName(d)} · ${area(d)}</td><td>${fmtTime(d.start)}–${fmtTime(d.end)}</td><td></td><td></td><td></td><td></td><td></td><td></td><td>☐</td><td>☐</td><td></td><td></td></tr>`).join('');
  const main=`<div class="doc-sub"><b>${esc(person.name)}</b> · Profil ${esc(profile.profileId)} · Zuerst die gesamte mögliche Zeit unter „Kann“ eintragen. „Wunsch“ liegt innerhalb dieses Rahmens; Sperren haben Vorrang.</div><table class="matrix-form-table"><thead><tr><th>Datum</th><th>Tag / Bereich</th><th>Rahmenzeit</th><th>Kann von</th><th>Kann bis</th><th>Wunsch von</th><th>Wunsch bis</th><th>Sperrzeit von</th><th>Sperrzeit bis</th><th>Sperrtag</th><th>Nur wenn nötig</th><th>V/H/B</th><th>Bemerkung</th></tr></thead><tbody>${rows}</tbody></table><div class="note">Wunsch = bevorzugte Einsatzzeit · Kann = gesamter möglicher Einsatzbereich · V = vorne · H = hinten · B = beides. Wenn V/H/B leer bleibt, gilt automatisch B.</div>`;
  const standbyRows=Array.from({length:6},()=>'<tr><td></td><td></td><td></td><td></td></tr>').join('');
  const guide=[['Kann von / bis','Gesamter möglicher Einsatzzeitraum','Hier darf grundsätzlich geplant werden.'],['Wunsch von / bis','Bevorzugte Einsatzzeit','Diese Zeit soll nach Möglichkeit zuerst berücksichtigt werden.'],['Sperrzeit von / bis','Innerhalb des Tages nicht verfügbar','In diesem Zeitraum darf nicht eingeplant werden.'],['Sperrtag','Ganzer Tag nicht verfügbar','Bei Ja wird der komplette Tag gesperrt.'],['Nur wenn nötig','Reserve','Die Kann-Zeit darf nur bei zusätzlichem Personalbedarf genutzt werden.'],['V / H / B','Einsatzbereich','V = vorne · H = hinten · B = beides. Leer wird als B gewertet.'],['Bemerkung','Zusätzlicher Hinweis','Nur wichtige Einschränkungen oder Absprachen eintragen.'],['Bereitschaftsdienst','Separater Bereitschaftszeitraum','Datum und Bereitschaft von/bis separat eintragen.']];
  const help=`<div class="doc-sub"><b>Bereitschaftsdienst</b> · ☐ grundsätzlich möglich · ☐ nur bestimmte Tage/Zeiten · ☐ kein Bereitschaftsdienst</div><table class="matrix-guide-table"><thead><tr><th>Datum</th><th>Bereitschaft von</th><th>Bereitschaft bis</th><th>Bemerkung</th></tr></thead><tbody>${standbyRows}</tbody></table><div class="doc-sub"><b>Anleitung zur Verfügbarkeitsmatrix</b> · Papierbogen und Excel verwenden dieselben Felder in derselben Reihenfolge.</div><table class="matrix-guide-table"><thead><tr><th>Feld</th><th>Bedeutung</th><th>So wird es ausgefüllt</th></tr></thead><tbody>${guide.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="note">Beispiel: Kann 14:00–22:00 · Wunsch 16:00–20:00 · V/H/B: H. Der QR-Code ordnet Foto oder Scan ausschließlich über Profil-ID, Formularversion und Zeitraum zu.</div>`;
  return{html:page('Persönliche Verfügbarkeitsmatrix · V12',person,profile,main,1,2)+page('Anleitung und Bereitschaft · V12',person,profile,help,2,2),fileName:`KC_DP2_Matrix_V12_${safe(person.name)}_${profile.profileId}.pdf`,qrMatrix,qrLabel:profile.profileId};
}
function gridTable(labels,columns=5){const rows=[];for(let i=0;i<labels.length;i+=columns)rows.push(`<tr>${labels.slice(i,i+columns).map(x=>`<td class="handwriting-field"><b>${esc(x)}</b></td>`).join('')}${'<td class="handwriting-field"></td>'.repeat(Math.max(0,columns-labels.slice(i,i+columns).length))}</tr>`);return `<table class="handwriting-table handwriting-section">${rows.join('')}</table>`}
function writingRows(labels){return `<table class="handwriting-table handwriting-section"><tbody>${labels.map(x=>`<tr><td><b>${esc(x)}</b></td><td class="handwriting-field"></td></tr>`).join('')}</tbody></table>`}
function writingSection(number,title,hint,content){return `<div class="note"><b>Bereich ${number}: ${esc(title)}</b>${hint?` - ${esc(hint)}`:''}</div>${content}`}
function legacyHandwritingDoc(person,profile,qrMatrix){
  const p1=`<div class="doc-sub"><b>${esc(person.name)}</b> · Persönliche Schriftprobe mit demselben Stift wie auf der Matrix ausfüllen.</div><div class="note">Ziffern jeweils dreimal schreiben. Typische Verwechslungen besonders deutlich trennen.</div>${gridTable('0123456789'.split(''),5)}<br><table class="handwriting-table"><tbody>${['0 / O','1 / I / l','2 / Z','5 / S','6 / G','9 / g'].map(x=>`<tr><td><b>${x}</b></td><td class="handwriting-field"></td></tr>`).join('')}</tbody></table>`;
  const p2=`<div class="doc-sub"><b>Buchstaben und Bereichskürzel</b></div>${gridTable('ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),5)}<br>${gridTable(['Ä','Ö','Ü','ä','ö','ü','ß','V = Vorne','H = Hinten','B = Beides (V/H)'],5)}`;
  const phrases=['08:00','14:30','18:00-23:00','04.12.2026','frei / Urlaub','gesperrt / Reserve','nur wenn nötig','Aufbau / Nachbereitung','Wunsch 14:00-16:00','Kann 14:00-20:00'];
  const p3=`<div class="doc-sub"><b>Uhrzeiten, Status und DP2-Praxis</b></div><table class="handwriting-table"><tbody>${phrases.map(x=>`<tr><td><b>${esc(x)}</b></td><td class="handwriting-field"></td></tr>`).join('')}</tbody></table><div class="note">Erkannte Schriftproben werden nicht automatisch in den Wunschplan übernommen. Jede Erkennung muss kontrolliert und bestätigt werden.</div>`;
  const html=[p1,p2,p3].map((body,i)=>page('Persönliche Handschriftprobe',person,profile,body,i+1,3)).join('');
  return{html,fileName:`KC_DP2_Handschriftprobe_${safe(person.name)}_${profile.profileId}.pdf`,qrMatrix,qrLabel:profile.profileId};
}
function handwritingDoc(person,profile,qrMatrix){
  const p1=`<div class="doc-sub"><b>${esc(person.name)}</b> - Bitte jeden Wert gut lesbar in seinem gerahmten Feld schreiben und denselben Stift wie auf der Matrix verwenden.</div>${writingSection(1,'Ziffern 0 bis 9','jede Ziffer dreimal in ihr Feld schreiben',gridTable('0123456789'.split(''),5))}${writingSection(2,'Uhrzeiten und Datum','die Beispiele vollst\u00e4ndig abschreiben',writingRows(['08:00','14:30','18:00-23:00','02.12.2026','14.12.2026']))}`;
  const p2=`<div class="doc-sub"><b>Buchstaben</b> - Gro\u00df- und Kleinbuchstaben werden bewusst in getrennten Bereichen erfasst.</div>${writingSection(3,'Gro\u00dfbuchstaben A bis Z','jeden Buchstaben einmal deutlich schreiben',gridTable('ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split(''),7))}${writingSection(4,'Kleinbuchstaben a bis z','einschlie\u00dflich Umlaute und sz',gridTable('abcdefghijklmnopqrstuvwxyz\u00e4\u00f6\u00fc\u00df'.split(''),7))}`;
  const p3=`<div class="doc-sub"><b>Verwechslungen und DP2-Praxis</b> - Zeichen und Begriffe jeweils in das zugeh\u00f6rige gerahmte Feld schreiben.</div>${writingSection(5,'Typische Verwechslungen','Zeichen klar voneinander unterscheiden',gridTable(['0 / O','1 / I / l','2 / Z','5 / S','6 / G','9 / g'],3))}${writingSection(6,'DP2-K\u00fcrzel und Begriffe','genau wie sp\u00e4ter auf dem Formular schreiben',gridTable(['V - H - B','Wunsch / Kann','Sperrtag / Sperrzeit','Nur wenn n\u00f6tig','Aufbau / Nachbereitung'],3))}<div class="note">Wichtig: Erkannte Schriftproben werden nie automatisch in den Wunschplan \u00fcbernommen. Jede Erkennung muss kontrolliert und best\u00e4tigt werden.</div>`;
  const html=[p1,p2,p3].map((body,i)=>page('Pers\u00f6nliche Handschriftprobe',person,profile,body,i+1,3)).join('');
  return{html,fileName:`KC_DP2_Handschriftprobe_${safe(person.name)}_${profile.profileId}.pdf`,qrMatrix,qrLabel:profile.profileId};
}
async function downloadPdf(kind,personId){const person=K.person?.(personId),profile=profileFor(person),qrMatrix=await qrFor(profile.payload),doc=kind==='matrix'?matrixDoc(person,profile,qrMatrix):handwritingDoc(person,profile,qrMatrix);return K.pdfAdapter.download(doc)}
async function downloadExcel(personId){
  const person=K.person?.(personId),profile=profileFor(person),qrMatrix=await qrFor(profile.payload),response=await fetch('templates/KC_DP2_Wunschzeiten_Vorlage_Weihnachtsmarkt_2026_V6_VHB.xlsx',{cache:'no-store'});if(!response.ok)throw new Error('Original-Excelmatrix konnte nicht geladen werden.');if(!window.JSZip)throw new Error('Excel-Komponente ist unvollständig.');
  const zip=await JSZip.loadAsync(await response.arrayBuffer()),read=async n=>zip.file(n).async('string'),xml=v=>esc(v).replace(/&#39;/g,'&apos;'),cell=(ref,value)=>`<c r="${ref}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`;
  let sheet=await read('xl/worksheets/sheet1.xml');const inject=(ref,value)=>{const row=Number(ref.match(/\d+/)[0]),re=new RegExp(`(<row\\b[^>]*r="${row}"[^>]*>)([\\s\\S]*?)(</row>)`);sheet=sheet.replace(re,(_,a,b,c)=>a+b.replace(new RegExp(`<c\\b[^>]*r="${ref}"[\\s\\S]*?</c>`),'')+cell(ref,value)+c)};inject('D4',person.name);inject('H4',profile.profileId);inject('D5',`${fmtDate(range().start)} bis ${fmtDate(range().end)}`);zip.file('xl/worksheets/sheet1.xml',sheet);
  let styles=await read('xl/styles.xml'),fillCount=Number(styles.match(/<fills count="(\d+)"/)?.[1]||0),xfCount=Number(styles.match(/<cellXfs count="(\d+)"/)?.[1]||0);styles=styles.replace(`<fills count="${fillCount}">`,`<fills count="${fillCount+1}">`).replace('</fills>','<fill><patternFill patternType="solid"><fgColor rgb="FF000000"/><bgColor indexed="64"/></patternFill></fill></fills>').replace(`<cellXfs count="${xfCount}">`,`<cellXfs count="${xfCount+1}">`).replace('</cellXfs>',`<xf numFmtId="0" fontId="0" fillId="${fillCount}" borderId="0" xfId="0" applyFill="1"/></cellXfs>`);zip.file('xl/styles.xml',styles);
  const letters=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s},info=[[1,'KC DP2 · QR-Identifikation'],[3,`Person: ${person.name}`],[4,`Profil-ID: ${profile.profileId}`],[5,`Zeitraum: ${fmtDate(range().start)} bis ${fmtDate(range().end)}`],[6,'QR enthält Profil-ID und Zeitraum, keinen ausgeschriebenen Namen.']],start=8,rows=info.map(([r,v])=>`<row r="${r}" ht="18" customHeight="1">${cell('A'+r,v)}</row>`);qrMatrix.forEach((line,r)=>rows.push(`<row r="${start+r}" ht="8" customHeight="1">${line.map((dark,c)=>dark?`<c r="${letters(c)}${start+r}" s="${xfCount}"/>`:'').join('')}</row>`));const endCol=letters(qrMatrix.length-1),qrSheet=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView showGridLines="0" workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><cols><col min="1" max="${qrMatrix.length}" width="1.15" customWidth="1"/></cols><sheetData>${rows.join('')}</sheetData><mergeCells count="5"><mergeCell ref="A1:${endCol}1"/><mergeCell ref="A3:${endCol}3"/><mergeCell ref="A4:${endCol}4"/><mergeCell ref="A5:${endCol}5"/><mergeCell ref="A6:${endCol}6"/></mergeCells><pageMargins left="0.3" right="0.3" top="0.4" bottom="0.4" header="0" footer="0"/><pageSetup orientation="portrait" fitToWidth="1" fitToHeight="1"/></worksheet>`;zip.file('xl/worksheets/sheet4.xml',qrSheet);
  zip.file('xl/workbook.xml',(await read('xl/workbook.xml')).replace('</sheets>','<sheet name="QR-Identifikation" sheetId="4" r:id="rId7"/></sheets>'));zip.file('xl/_rels/workbook.xml.rels',(await read('xl/_rels/workbook.xml.rels')).replace('</Relationships>','<Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet4.xml"/></Relationships>'));zip.file('[Content_Types].xml',(await read('[Content_Types].xml')).replace('</Types>','<Override PartName="/xl/worksheets/sheet4.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>'));
  const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'}),fileName=`KC_DP2_Wunschmatrix_${safe(person.name)}_${profile.profileId}.xlsx`,url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);return{fileName,bytes:blob.size};
}
async function downloadAll(personId,onStep){const tasks=[['PDF-Matrix',()=>downloadPdf('matrix',personId)],['Excel-Matrix',()=>downloadExcel(personId)],['Handschriftprobe',()=>downloadPdf('handwriting',personId)]];const result=[];for(let i=0;i<tasks.length;i++){onStep?.(i,tasks[i][0]);result.push(await tasks[i][1]());await new Promise(r=>setTimeout(r,250))}onStep?.(tasks.length,'Fertig');return result}
K.personalizedForms={version:'0.20.0-b238',profileFor,qrFor,downloadPdf,downloadExcel,downloadAll,_test:{matrixDoc,handwritingDoc}};
})();
