(()=>{
 const STORE='kc_dp_mobile_entry_v1',BUILD='0.19.51-mobile-secure4',SUPA='https://ptblnpiroqftcvlsrhac.supabase.co/functions/v1/';
 const $=id=>document.getElementById(id),show=id=>$(id).classList.remove('hide'),hide=id=>$(id).classList.add('hide');
 const ios=/iPhone|iPad|iPod/i.test(navigator.userAgent||'')||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),android=/Android/i.test(navigator.userAgent||'');
 const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
 const q=new URL(location.href).searchParams.get('entry')||'',valid=/^kc-dp-i-[a-z0-9]{12,40}$/.test(q);if(valid)localStorage.setItem(STORE,q);const entry=valid?q:(localStorage.getItem(STORE)||'');
 let END='',server=null,deferred=null,lastError=null,lastStep='start';
 function device(){return ios?'handy:ios':android?'handy:android':'handy:other'}
 function friendly(e){const m=String(e?.message||e||'');if(/Erlauben|genehmigt|permission/i.test(m))return'Benachrichtigungen sind noch nicht erlaubt. Bitte noch einmal versuchen und „Erlauben“ wählen.';if(/Installation|install/i.test(m))return'Die Installation konnte noch nicht abgeschlossen werden. Bitte noch einmal versuchen.';if(/Push|Testnachricht/i.test(m))return'Die Testnachricht konnte gerade nicht gesendet oder bestätigt werden.';if(/Verbindung|fetch|Netz|502|503|504/i.test(m))return'Die Verbindung zum DP2-Server hat gerade nicht funktioniert.';return'DP2 konnte diesen Schritt noch nicht abschließen.'}
 function allHide(){['load','iosInstall','androidInstall','push','access','cancelled','error'].forEach(hide)}
 function fail(e,step=lastStep){lastError=e;lastStep=step;allHide();$('errorText').textContent=friendly(e);$('reportState').textContent='';hide('reportState');$('report').style.display=navigator.onLine?'block':'none';show('error')}
 async function call(action,p={}){const r=await fetch(END,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,device:device(),deviceClass:'handy',installed:standalone(),notification:typeof Notification==='undefined'?'unsupported':Notification.permission,targetVersion:'0.19.51',pilotBuild:BUILD,...p})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Verbindung fehlgeschlagen (${r.status})`);return d}
 function b64u(s){const pad='='.repeat((4-s.length%4)%4),raw=atob((s+pad).replace(/-/g,'+').replace(/_/g,'/')),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
 async function registerWorker(){if(!('serviceWorker'in navigator))throw Error('Service Worker nicht verfügbar.');const reg=await navigator.serviceWorker.register(`./sw.js?entry=${encodeURIComponent(entry)}&v=4`,{scope:'./',updateViaCache:'none'});await navigator.serviceWorker.ready;return reg}
 async function subscribe(){lastStep='push_anmelden';const reg=await registerWorker();let s=await reg.pushManager.getSubscription();if(!s)s=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64u(server.vapidPublicKey)});await call('subscribe',{subscription:s.toJSON?s.toJSON():s,userAgent:navigator.userAgent})}
 function renderAccess(x=server||{}){allHide();show('access');const mode=String(x.accessMode||server?.accessMode||'none');$('openBtn').classList.add('hide');if(mode==='member'){$('accessIcon').textContent='✅';$('accessTitle').textContent='KC DP2 ist installiert';$('accessText').textContent='Für dieses Gerät ist ein Mitgliederzugang vorgesehen. Das Programm öffnet sich mit der persönlichen Anmeldung.';$('openBtn').textContent='KC DP2 ÖFFNEN';$('openBtn').onclick=()=>location.href='../index.html';$('openBtn').classList.remove('hide');return}if(mode==='test'){$('accessIcon').textContent='🧪';$('accessTitle').textContent='Testzugang bereit';$('accessText').textContent='Der Testzugang arbeitet getrennt von den echten Köcheclub-Daten und hat keine Verwaltungsrechte.';$('openBtn').textContent='TESTZUGANG ÖFFNEN';$('openBtn').onclick=()=>location.href='./test.html';$('openBtn').classList.remove('hide');return}$('accessIcon').textContent='✅';$('accessTitle').textContent='KC DP2 ist installiert';$('accessText').textContent='Für dieses Gerät ist noch kein Benutzerzugang freigeschaltet. Die App und Push funktionieren, Köcheclub-Daten bleiben gesperrt.'}
 async function waitForStatus(wanted,tries=20){for(let i=0;i<tries;i++){await new Promise(r=>setTimeout(r,900));const x=await call('bootstrap');server={...server,...x};if(wanted.includes(String(x.status||'')))return x}return null}
 async function finishAfterTest(){lastStep='abschluss';try{const b=await call('bootstrap');server={...server,...b};if(b.status==='test_received'){try{await call('finish');await waitForStatus(['completed'],10)}catch(_){} }renderAccess(server)}catch(_){renderAccess(server)}}
 async function pollTest(){lastStep='push_pruefen';const x=await waitForStatus(['test_received','completed'],25);if(!x)throw Error('Die Testnachricht wurde noch nicht bestätigt.');await finishAfterTest()}
 async function allowPush(){lastStep='push_freigeben';try{allHide();show('load');$('load').textContent='Bitte „Erlauben“ wählen …';if(typeof Notification==='undefined')throw Error('Benachrichtigungen sind auf diesem Gerät nicht verfügbar.');if(Notification.permission!=='granted'){const p=await Notification.requestPermission();if(p!=='granted')throw Error('Bitte „Erlauben“ wählen.')}$('load').textContent='Wird automatisch fertiggestellt …';await call('installed',{installedVersion:'0.19.51',installDisposition:standalone()?'standalone':'installed'});await subscribe();lastStep='test_push_senden';const b=await call('bootstrap');server={...server,...b};if(['test_received','completed'].includes(String(b.status||''))){await finishAfterTest();return}const r=await call('send_test');if(!(r.sent>0))throw Error('Push konnte nicht gesendet werden.');$('load').textContent='Push wird geprüft …';await pollTest()}catch(e){fail(e,lastStep)}}
 async function installAndroid(){lastStep='installation';try{allHide();show('load');if(standalone()){allHide();show('push');return}if(!deferred){await new Promise(r=>setTimeout(r,700));if(!deferred)throw Error('Installation ist noch nicht bereit. Bitte noch einmal versuchen.')}await deferred.prompt();const c=await deferred.userChoice;if(c?.outcome!=='accepted')throw Error('Installation wurde nicht bestätigt.');deferred=null;$('load').textContent='Installation abgeschlossen.';setTimeout(()=>{allHide();show('push')},350)}catch(e){fail(e,'installation')}}
 async function boot(){lastStep='start';try{if(!entry)throw Error('Persönlicher Testzugang fehlt.');END=SUPA+entry+'/';allHide();show('load');await registerWorker();server=await call('bootstrap');$('name').textContent='Hallo '+(server.firstName||'');await call('heartbeat',{phase:'mobile_secure_boot',selectedDeviceClass:'handy'}).catch(()=>{});if(server.status==='test_received'){await finishAfterTest();return}if(server.status==='completed'){renderAccess(server);return}allHide();if(standalone()){if(typeof Notification!=='undefined'&&Notification.permission==='granted')allowPush();else show('push')}else if(ios)show('iosInstall');else if(android)show('androidInstall');else throw Error('Dieser Testlink ist für ein Handy vorgesehen.')}catch(e){fail(e,'start')}}
 async function report(){if(!lastError)return;try{$('report').disabled=true;const r=await call('report_error',{step:lastStep,errorCode:lastError?.name||'client_error',errorMessage:String(lastError?.message||lastError).slice(0,300),userAgent:navigator.userAgent,online:navigator.onLine});$('reportState').textContent=r.reported?'Meldung wurde gesendet.':'Meldung konnte nicht gesendet werden.';show('reportState')}catch(_){$('reportState').textContent='Meldung konnte gerade nicht gesendet werden.';show('reportState')}finally{$('report').disabled=false}}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e});
 window.addEventListener('appinstalled',()=>{allHide();show('push')});
 $('installBtn').onclick=installAndroid;$('pushBtn').onclick=allowPush;$('retry').onclick=()=>{hide('error');lastStep==='start'?boot():(lastStep==='installation'?installAndroid():allowPush())};$('abort').onclick=()=>{allHide();show('cancelled')};$('report').onclick=report;
 boot();
})();
