import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'tmp/twinkey-qa');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.route('http://matrix.test/**',async route=>{try{await route.fulfill({body:await readFile(path.join(root,new URL(route.request().url()).pathname.slice(1))),contentType:route.request().url().endsWith('.svg')?'image/svg+xml':'image/webp'})}catch{await route.abort()}});
 await page.setContent('<html><head><base href="http://matrix.test/"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="kcdpUxRoot"></div></body></html>');
 const html=await readFile(path.join(root,'index.html'),'utf8');for(const file of [...html.matchAll(/<link[^>]+href="([^"?]+\.css)[^"]*"/g)].map(x=>x[1]).filter(x=>!x.startsWith('http')))await page.addStyleTag({content:await readFile(path.join(root,file),'utf8')});
 await page.evaluate(()=>{window.KCDP={twinkeyUseDeviceVoice:true,days:[{date:'2026-12-04',start:11,end:23,type:'market'},{date:'2026-12-05',start:11,end:23,type:'market'}],people:[{personId:'me',name:'Hans Beispiel',active:true,personType:'member'},{personId:'friend',name:'Bernd Beispiel',active:true,personType:'member'}],currentUser:{personId:'me',displayName:'Hans Beispiel',role:'employee'},state:{wishPhase:'open'},workflow:{status:'draft'},wishes:[],shifts:[],eventConfig:{name:'Weihnachtsmarkt 2026'},memberUxData:{},persistAll:async()=>{},requirementFor:()=>({total:2}),person(id){return this.people.find(p=>p.personId===id)}};window.speechLog=[];window.stopCount=0;Object.defineProperty(window,'speechSynthesis',{value:{cancel(){window.stopCount++},getVoices(){return[{lang:'de-DE',localService:true}]},speak(u){window.speechLog.push(u.text);u.onstart?.()}}});window.SpeechSynthesisUtterance=class{constructor(text){this.text=text}};});
 for(const file of ['src/core/wish-contract.js','src/core/auth.js','src/core/workflow.js','src/core/actual.js','src/core/mobile-wish-matrix.js','src/ui/role-ux.js','src/ui/mobile-wish-matrix.js','src/ui/wish-assistant.js','src/ui/chef-companion.js','src/ui/twinkey.js'])await page.addScriptTag({content:await readFile(path.join(root,file),'utf8')});
 await page.evaluate(()=>{const K=KCDP;K.validateWish=w=>K.wishContract.validate(w);K.latestPublishedVersion=()=>K.testPublished||null;K.wishes=[{id:'W1',personId:'me',date:'2026-12-04',start:12,end:18,wishType:'available',status:'confirmed',wishZone:'B'}];K.roleUx.showRoleHome()});
 assert.match(await page.locator('.chef-helper').innerText(),/Hallo Hans.*Twinkey/s);assert(await page.locator('#twNext').isDisabled());assert.equal(await page.evaluate(()=>speechLog.length),0,'Voice must stay off until opted in');
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Welcome overflow '+width)}await page.setViewportSize({width:390,height:844});
 await page.locator('#twVoice').click();assert.equal(await page.evaluate(()=>speechLog.length),1);await page.locator('#twRepeat').click();assert.equal(await page.evaluate(()=>speechLog.length),2);await page.locator('#twStop').click();assert.equal(await page.locator('.tw-wave.speaking').count(),0);
 await page.locator('[data-tw-mode=guided]').click();assert.equal(await page.locator('[data-tw-task]').count(),4);await page.screenshot({path:path.join(out,'Twinkey-Begruessung-Handy.png'),fullPage:true});
 assert.equal(await page.locator('[data-tw-task]').count(),4);await page.screenshot({path:path.join(out,'Twinkey-Auswahl-Handy.png'),fullPage:true});await page.locator('[data-tw-task=wish]').click();await page.locator('[data-wa-day="2026-12-04"]').click();assert.match(await page.locator('.wa-existing').innerText(),/12:00–18:00/);
 await page.locator('[data-choice=status][data-value=yes]').click();
 const startField=page.locator('[data-slot-key=can][data-slot-field=start]'),endField=page.locator('[data-slot-key=can][data-slot-field=end]');
 assert.equal(await startField.locator('option').nth(1).getAttribute('value'),'11');await startField.selectOption('11');await endField.selectOption('19');assert.match(await page.locator('#waCurrentSummary').innerText(),/11:00–19:00/);assert.match(await page.locator('#waCurrentSummary').innerText(),/Noch nicht gespeichert/);assert.equal(await startField.evaluate(x=>x.getBoundingClientRect().height>=48),true);
 await page.locator('[data-other-time="can:0"]').click();assert.equal(await startField.locator('option').nth(1).getAttribute('value'),'0');await page.locator('[data-other-time="can:0"]').click();
 await page.screenshot({path:path.join(out,'Twinkey-Zeiten-Handy.png'),fullPage:true});
 // Existing normal navigation must confirm before throwing away the draft.
 page.once('dialog',d=>d.dismiss());await page.locator('[data-nav=home]').click();assert(await page.locator('#waCancel').isVisible());page.once('dialog',d=>d.accept());await page.locator('[data-nav=home]').click();assert.equal(await page.locator('[data-tw-task]').count(),4);
 await page.evaluate(()=>{const K=KCDP,s={id:'S1',personId:'me',date:'2026-12-04',start:12,end:18,layer:'planned',status:'published',area:'Verkauf'};K.shifts=[s];K.testPublished={version:1,shifts:[{...s}]};K.shifts[0].end=20;});
 await page.locator('[data-tw-task=plan]').click();assert.match(await page.locator('.tw-row').innerText(),/12:00–18:00/);assert.doesNotMatch(await page.locator('.tw-row').innerText(),/20:00/);await page.locator('#twTasks').click();
 await page.locator('[data-tw-task=change]').click();await page.locator('[data-tw-shift]').click();await page.locator('[data-tw-reason="0"]').click();await page.locator('#twRequest').click();assert.match(await page.locator('#twRequestStatus').innerText(),/geändert/);assert.equal(await page.evaluate(()=>KCDP.swapRequests.length),0);
 await page.evaluate(()=>KCDP.shifts[0].end=18);await page.locator('#twRequest').click();await page.waitForSelector('#twAnother');assert.equal(await page.evaluate(()=>KCDP.swapRequests.length),1);await page.locator('#twAnother').click();assert.match(await page.locator('.tw-row').innerText(),/bereits offen/);await page.locator('#twTasks').click();
 await page.evaluate(()=>KCDP.actualShifts=[{id:'A1',personId:'me',date:'2026-12-04',start:12,end:16,status:'recorded'},{id:'A2',personId:'friend',date:'2026-12-04',start:9,end:23,status:'recorded'}]);await page.locator('[data-tw-task=actual]').click();assert.match(await page.locator('#twActualRows').innerText(),/4 Stunden/);assert.doesNotMatch(await page.locator('#twActualRows').innerText(),/09:00|23:00/);
 await page.evaluate(()=>{KCDP.twinkey.reset();KCDP.roleUx.showRoleHome()});await page.locator('#twSkip').click();assert(await page.locator('#uxStartTimes').isVisible());assert.equal(await page.locator('#twNext').count(),0);await page.locator('#uxTwinkey').click();assert.equal(await page.locator('[data-tw-task]').count(),4);
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('#twNext').evaluate(x=>getComputedStyle(x).animationName),'none');await page.locator('[data-tw-task=wish]').click();
 await page.evaluate(()=>{KCDP.twinkey.reset();Object.defineProperty(window,'SpeechSynthesisUtterance',{value:undefined});KCDP.roleUx.showRoleHome()});assert(await page.locator('#twVoice').isDisabled());assert.match(await page.locator('#twVoice').innerText(),/nicht verfügbar/);
 assert.deepEqual(errors,[]);console.log('Twinkey browser checks passed: welcome, skip/restart, opt-in voice/repeat/stop, four routes, saved data, draft guard, published plan, request validation, own actuals, responsive/reduced motion.');
}finally{await browser.close()}
